### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by skiddy1903** [stephen/airsonos#136]
really sorry if this issue has already been discussed but i couldn't find a similar error in the previous posts.

i'm trying to install airsonos on my macbook but i'm getting install errors. i'm not experienced at this sort of thing so any help would be appreciated.  here's the log;

Last login: Fri Mar 20 16:47:49 on ttys001
unknown-00:1e:c2:a1:ac:49:~ mske$ sudo npm install airsonos -g
npm http GET https://registry.npmjs.org/airsonos
npm http 304 https://registry.npmjs.org/airsonos
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/nicercast
npm http GET https://registry.npmjs.org/nodetunes
npm http GET https://registry.npmjs.org/portastic
npm http GET https://registry.npmjs.org/throttle
npm http GET https://registry.npmjs.org/flags
npm http GET https://registry.npmjs.org/ip
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/stephen/node-sonos.git) 
npm ERR! git clone git://github.com/stephen/node-sonos.git 
npm ERR! Error: Command failed: 
npm ERR!     at ChildProcess.exithandler (child_process.js:647:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:753:16)
npm ERR!     at Socket.<anonymous> (child_process.js:966:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 10.8.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/mske
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/nodetunes
npm http 304 https://registry.npmjs.org/portastic
npm http 304 https://registry.npmjs.org/throttle
npm http 304 https://registry.npmjs.org/flags
npm http 304 https://registry.npmjs.org/ip
npm http 304 https://registry.npmjs.org/nicercast
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mske/npm-debug.log
npm ERR! not ok code 0

**Comment by skiddy1903** [comment]
I'm going to close this issue myself. I figured out what was going on it was my version of git not working with my version of OS X.

Still not got airsonos working yet but the errors I'm now getting are discussed in other threads. Just working through the suggestions so hopefully I'll be up and running soon.
