### ISSUE TITLE
Windows DNS Issue

### ISSUE THREAD

**Issue by Lamasticot** [stephen/airsonos#143]
My issue is pretty frustrating because there isn't a real problem, maybe just a bug but it persist...

C:\Users\Utilisateur>where airsonos
C:\Users\Utilisateur\AppData\Roaming\npm\airsonos
C:\Users\Utilisateur\AppData\Roaming\npm\airsonos.cmd

C:\Users\Utilisateur>airsonos
Unexpected result while probing for avahi: { [Error: dns service error: unknown
error code] errorCode: -65563 }
Searching for Sonos devices on network...
Setting up AirSonos for Salle de bains {192.168.1.33:1400}

Error: dns service error: unknown error code
    at new Advertisement (C:\Users\Utilisateur\AppData\Roaming\npm\node_modules\
airsonos\node_modules\nodetunes\node_modules\mdns\lib\advertisement.js:56:10)
    at Object.create [as createAdvertisement] (C:\Users\Utilisateur\AppData\Roam
ing\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\adver
tisement.js:64:10)
    at NodeTunes.<anonymous> (C:\Users\Utilisateur\AppData\Roaming\npm\node_modu
les\airsonos\node_modules\nodetunes\lib\server.js:65:21)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)

**Comment by stephen** [comment]
Unfortunately, this is an issue with the mdns module, not airsonos directly.

See: https://github.com/agnat/node_mdns/issues/104
