### ISSUE TITLE
raspberry pi install - module.js:340 throw error

### ISSUE THREAD

**Issue by Mcmonanecka** [stephen/airsonos#196]
I've been trying to install Airsonos on a raspberry pi 2 B+. But getting an error message when it comes to running the software. I've installed mostly by following this guide:
http://www.schrankmonster.de/2014/06/25/raspberrypi-sonos-speakers-support-apple-airplay/

Installed node 0.10.33 using this guide:
http://www.armhf.com/node-js-for-the-beaglebone-black/
(I installed node before avahi)

and installing lirenzhu's version of airsonos with the node songs fix:
1. Download it as a zip (https://github.com/lirenzhu/airsonos/archive/with-node-sonos-fix.zip)
2. Unzip the project
3. Use console to run npm install in the unzipped project directory
4. node index.js

But then I'm getting this error message:
pi@raspberrypi ~ $ node -v
v0.10.33
pi@raspberrypi ~ $ npm -v
1.1.4
pi@raspberrypi ~ $ cd airsonos-with-node-sonos-fix
pi@raspberrypi ~/airsonos-with-node-sonos-fix $ node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/airsonos-with-node-sonos-fix/node_modules/nodetunes/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

I've done a search on the pi for "dans_sd_bindings" but can't find it on my pi. Any suggestions?

Cheers M

**Comment by Mcmonanecka** [comment]
after some more experimenting the error has changed to:

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/pi/lib/main'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/index.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
