### ISSUE TITLE
Error: Method Not Allowed

### ISSUE THREAD

**Issue by mjm8975** [stephen/airsonos#202]
Hi,

Anyone any ideas what is going wrong here? Im using node version v0.12.7

Searching for Sonos devices on network...

/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:673
            throw e;
                  ^
Error: Method Not Allowed
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)

**Comment by Martin-JC** [comment]
I have just got airsonos installed and have exactly the same problem.  Did you find a solution?  I am also on node v0.12.7 (git 1.9.1, npm 3.3.9, nvm 0.29.0, node-gyp 0.10.10, Ubuntu 14.04.3 LTS 64 bit)

**Comment by mjm8975** [comment]
No I never did get it working. After trying numerous different things I now get a "-bash: airsonos: command not found" when typing airsonos in terminal.

**Comment by ColinRioux** [comment]
@mjm8975 when you get `-bash: airsonos: command not found` it simply means airsonos is either no longer installed or it's no longer installed globally (`-g` flag)
