### ISSUE TITLE
Airsonos 0.2.2 EventEmitter Memory Leak error

### ISSUE THREAD

**Issue by ambledown** [stephen/airsonos#207]
Happens every couple of hours. Will just quit playing. Error code below: 

Middle-Wests-Mini:~ middlewest$ airsonos
Searching for Sonos devices on network...

Office (@ 10.1.10.22:1400, RINCON_B8E9373D404001400:12)

Search complete. Set up 1 device tunnel.
(node) warning: possible EventEmitter memory leak detected. 11 clientDisconnected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at NodeTunes.addListener (events.js:179:15)
    at DeviceTunnel.handleClientConnected (/usr/local/lib/node_modules/airsonos/bin/tunnel.js:93:26)
    at NodeTunes.emit (events.js:107:17)
    at announceParse (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:133:25)
    at announce (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:79:7)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:62:7)
    at ServerParser.emit (events.js:110:17)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ServerParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
(node) warning: possible EventEmitter memory leak detected. 11 metadataChange listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at NodeTunes.addListener (events.js:179:15)
    at DeviceTunnel.handleClientConnected (/usr/local/lib/node_modules/airsonos/bin/tunnel.js:84:26)
    at NodeTunes.emit (events.js:107:17)
    at announceParse (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:133:25)
    at announce (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:79:7)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:62:7)
    at ServerParser.emit (events.js:110:17)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ServerParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

**Comment by lirenzhu** [comment]
Confirming

Steps to reproduce:
1. Start airsonos
2. AirPlay to an AirSonos device
3. Disconnect
4. Repeat steps 2 and 3, 10 more times

**Comment by kjwierenga** [comment]
+1
