### ISSUE TITLE
Process exits when netstat run against host

### ISSUE THREAD

**Issue by reub** [stephen/airsonos#208]
airsonos seems to fail with the following output when the machine running it (OSX 10.10.5 in my case) is scanned by netstat

```error
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```

Let me know if further debug info would be useful.

**Comment by stephen** [comment]
Hm, I'm unable to reproduce this locally.

Can you provide `--verbose` output from airsonos when this occurs?

**Comment by reub** [comment]
@stephen Apologies. I meant nmap, not netstat.

Here is the output I'm seeing. Note I've masked some ids. If those are pertinent to your debugging, please contact via my username on twitter and I will supply the unmasked output.

1) Laptop Running airsonos:
```
myid@laptop:~$ airsonos --version
0.2.2

myid@laptop:~$ airsonos --verbose
Searching for Sonos devices on network...

  nodetunes:server starting nodetunes server (Downstairs (AirSonos)) +0ms
  nodetunes:server broadcasting mdns advertisement (for port 5000) +13ms
  nodetunes:server starting nodetunes server (Back Bedroom (AirSonos)) +8ms
  nodetunes:server starting nodetunes server (Bathroom (AirSonos)) +0ms
  nodetunes:server starting nodetunes server (Front Bedroom (AirSonos)) +0ms
Bathroom (@ 192.168.9.114:1400, RINCON_<MASKED>:12)
Front Bedroom (@ 192.168.9.213:1400, RINCON_<MASKED>:15)
Back Bedroom (@ 192.168.9.3:1400, RINCON_<MASKED>:18)
Downstairs (@ 192.168.9.212:1400, RINCON_<MASKED>:11)

Search complete. Set up 4 device tunnels.
  nodetunes:server broadcasting mdns advertisement (for port 5003) +20ms
  nodetunes:server broadcasting mdns advertisement (for port 5001) +1ms
  nodetunes:server broadcasting mdns advertisement (for port 5002) +0ms
```


2) Scanning Machine:
```
myid@server:~$ nmap --version

Nmap version 6.40 ( http://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.2.3 openssl-1.0.1f libpcre-8.31 libpcap-1.5.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

myid@server:~$ nmap -v -A laptop
```

3) Laptop Running airsonos:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
myid@laptop:~$
```
