### ISSUE TITLE
AirSonos crashing when playing iTunes from airsonos server OK from IOS devices

### ISSUE THREAD

**Issue by njhcarroll** [stephen/airsonos#209]
Hi  I have Airsonos (Brilliant app) installed on a mac mini running OSX El Capitan.  The server works fine when playing tunes from iOS devices but crashes if I try to play via iTunes on the mac mini.  Below is the crash text when running airsonos in verbose mode.   Any ideas?
Thanks
  
  nodetunes:server starting nodetunes server (Kitchen (AirSonos)) +0ms
Kitchen (@ 192.168.1.83:1400, RINCON_000E5870DB7C01400:3)

Search complete. Set up 1 device tunnel.
  nodetunes:server broadcasting mdns advertisement (for port 5000) +21ms
  nodetunes:rtsp received method OPTIONS (CSeq: 1)
{ cseq: '1',
  'user-agent': 'iTunes/12.2.2 (Macintosh; OS X 10.11)',
  'client-instance': '85088D85FB0B9C5F',
  'dacp-id': '85088D85FB0B9C5F',
  'active-remote': '1803040664',
  'apple-challenge': 'Z0pfY99qAsf75FKohSmEiQ' } +7s
  nodetunes:helper building challenge for Z0pfY99qAsf75FKohSmEiQ== (ip: c0a80157, mac: 54520046032f) +2ms
  nodetunes:helper computed challenge: ti/hVPmXfHyBY0ZT3mvOVRAyNIOjea6gztDqABF6/bNbh/8djiZ+gArdngq+cLJSQipayJTRYc7bA5KTyEu0Z8GNQYpushph026Yo4C4tL8eRWciIiPPEX5E/Oaf54qYPEjCadj/zj1Gg3whu4Wu6k32Ez5QQ+ndcaon0Aq3w3kQhRGoaRPaHfClpcLaOQiXyfo/Qt8aKxx6GH5YG3fYUx1C8QAlgexn8WdwomC/IkagKwdzwbOuqoZVjspujze2gPVPcKCLvdkalR/HLpZvudTLv9uGQJ9zT3Bbb+JwNa3qofGjQBJSQVjo6otwGTPFVuiS6haHWyuTGyIBOVGIiA== +79ms
  nodetunes:rtsp received method ANNOUNCE (CSeq: 1)
{ cseq: '1',
  'content-type': 'application/sdp',
  'content-length': '570',
  'user-agent': 'iTunes/12.2.2 (Macintosh; OS X 10.11)',
  'client-instance': '85088D85FB0B9C5F',
  'dacp-id': '85088D85FB0B9C5F',
  'active-remote': '1803040664' } +2s
  nodetunes:rtspmethods v=0
o=iTunes 3524229722 0 IN IP4 192.168.1.87
s=iTunes
c=IN IP4 192.168.1.87
t=0 0
m=audio 0 RTP/AVP 96
a=rtpmap:96 AppleLossless
a=fmtp:96 352 0 16 40 10 14 2 255 0 0 44100
a=rsaaeskey:DBo3K7EyRosQAaElPSLLJPtvtkeivN53+xsHcdnTzjeG2RxeeDGEf6NnZtxqSRl9VkdSHZPlIkr7bhNvvlgFDQxhkECUPmkQ/fi8ZIvSP/VH1/m4tx01xzNGcjmNEHegXQBk6ezYTinB/gephv1Hl1eH8VpkMe0J/GNlwSPCOqKlVsro4/r4ptBpbXwLhJEw1FdPMVxSgcTE9uozrhZrYUN+YwN6FCGbiESz8dVLJl+SBDC3VM5Ma+L4rZgMtAPD2zVKcwzFKHr7LyNBORzdc6OYhrMwzLN49XWafZNnJLOWDzCxaieKNhefTstb9V3a/7ixjQEH4fiUaoYqCyFtCQ
a=aesiv:fegLJi8i7jXzGpGBcUImAA
 +0ms
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at DeviceTunnel.emit (events.js:87:13)
    at NodeTunes.emit (events.js:107:17)
    at announceParse (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:105:31)
    at announce (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:79:7)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:62:7)
    at ServerParser.emit (events.js:110:17)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ServerParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

**Comment by tobyboreham** [comment]
+1 on this. As OP said, works great from iOS, but iTunes from both OS X and Windows crash it.

Error: Uncaught, unspecified "error" event.
    at Error (native)
    at DeviceTunnel.emit (events.js:87:13)
    at NodeTunes.emit (events.js:107:17)
    at announceParse (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:105:31)
    at announce (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:79:7)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:62:7)
    at ServerParser.emit (events.js:110:17)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ServerParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

**Comment by stephen** [comment]
#9
