### ISSUE TITLE
Errors building on OSX Darwin

### ISSUE THREAD

**Issue by WizGnome** [stephen/airsonos#210]
Hi,

I am having problems trying to build airsonos:

22 error Darwin 14.5.0
23 error argv "node" "/usr/local/bin/npm" "install" "-g"
24 error node v0.12.7
25 error npm  v2.11.3
26 error file sh
27 error code ELIFECYCLE
28 error errno ENOENT
29 error syscall spawn
30 error airsonos@0.2.2 prepublish: `babel ./lib/ -d ./bin/`
30 error spawn ENOENT
31 error Failed at the airsonos@0.2.2 prepublish script 'babel ./lib/ -d ./bin/'.
31 error This is most likely a problem with the airsonos package,
31 error not with npm itself.
31 error Tell the author that this fails on your system:
31 error     babel ./lib/ -d ./bin/
31 error You can get their info via:
31 error     npm owner ls airsonos
31 error There is likely additional logging output above.
32 verbose exit [ 1, true ]

**Comment by stephen** [comment]
@WizGnome - can you provide the full log? This looks like a partial output.

**Comment by WizGnome** [comment]
I have just updated xcode and tried building again, It now builds (with a few warnings) - unfortunately I am not at home where I have my Sonos - will try when I get back and see if it is now working.

**Comment by WizGnome** [comment]
When I try and play to the device, I now get this error:

MacBook-Pro:~ wilsonmic$ airsonos
Searching for Sonos devices on network...

Portable (@ 192.168.1.44:1400, RINCON_B8E937B02E8A01400:1)

Search complete. Set up 1 device tunnel.
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at DeviceTunnel.emit (events.js:87:13)
    at NodeTunes.emit (events.js:107:17)
    at announceParse (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:105:31)
    at announce (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:79:7)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:62:7)
    at ServerParser.emit (events.js:110:17)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ServerParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
