### ISSUE TITLE
Bluebird error using 0.2.2 airsonos version

### ISSUE THREAD

**Issue by sportsnapper** [stephen/airsonos#211]
I've just tried to upgrade to the latest 0.2.2 version of airsonos. Though it builds, when I execute airsonos it fails with the following error which looks like it's in the bluebird module:
```
Searching for Sonos devices on network...


/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
                  ^
Error: Method Not Allowed
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)
```

The build shows these module versions
```
airsonos@0.2.2 /usr/local/lib/node_modules/airsonos
├── ip@0.3.2
├── flags@0.1.3
├── bluebird@2.10.0
├── sonos@0.7.0 (debug@0.7.4, underscore@1.5.2, async@0.9.2, upnp-client@0.0.1, xml2js@0.2.8, request@2.27.0)
├── nodetunes@0.2.0 (random-mac@0.0.4, randomstring@1.0.3, metricstream@0.0.0, priorityqueuejs@0.2.0, httplike@1.0.2, ipaddr.js@1.0.3, debug@2.2.0, portastic@0.0.1, node-forge@0.6.34, forge@2.3.0, mdns@2.2.2)
├── babel@5.8.23 (slash@1.0.0, path-exists@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.1, commander@2.8.1, source-map@0.4.4, output-file-sync@1.1.1, glob@5.0.14, lodash@3.10.1, babel-core@5.8.23, chokidar@1.0.5)
└── nicercast@0.1.0 (icecast-stack@0.3.0, express@3.5.3, lame@1.2.3)
```

this seems at odds with the package.json file, which wants bluebird 2.9.34 - how can I force the build to use this version of bluebird. 

I'm building using 
    sudo npm install -g --force airsonos

node version 0.12.7
npm version 2.11.3

**Comment by mjm8975** [comment]
Did you get anywhere with this as I am getting the same:

`/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
                  ^
Error: Method Not Allowed
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)`

**Comment by richardtape** [comment]
Ditto.

```
node ./bin/index.js
Searching for Sonos devices on network...


/Users/richardtape/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
Error: Internal Server Error
    at maybeWrapAsError (/Users/richardtape/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /Users/richardtape/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /Users/richardtape/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /Users/richardtape/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /Users/richardtape/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /Users/richardtape/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/Users/richardtape/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/Users/richardtape/airsonos/node_modules/request/request.js:129:22)
```

```
node --version
v5.1.0
```

```
npm --version
3.3.12
```

```
npm install bluebird -g
/usr/local/lib
└── bluebird@3.1.1
```

Mac OSX 10.10.5

Any ideas? Anything I can throw your way to help with this?

**Comment by gazzer82** [comment]
Did anyone get anywhere with this, i am seeing the same issue?

**Comment by jordn** [comment]
+1

**Comment by lucdetellis** [comment]
+1, same issue
