### ISSUE TITLE
Error when launching airsonos

### ISSUE THREAD

**Issue by bdsousa** [stephen/airsonos#216]
Hi,

i'm getting this message after installing airsonos on my mac. (i tried many ways and i really don't know if it's correctly installed)

Can you help ?

$ airsonos
Searching for Sonos devices on network...

/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
                  ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)

**Comment by mgregor** [comment]
mee too

**Comment by scherii** [comment]
Exactly the same as @bdsousa on OS X 10.11 open beta.
Tried with node v0.12 and v4.1.1.

My SONOS system is on build/version 29699020 (6.0).

**Comment by dsarel10** [comment]
I also have the same issue on Ubuntu 14.04

**Comment by dsarel10** [comment]
I also get this error on OS X 10.11.1 with node v0.12.7 after installing with:
```
sudo npm install airsonos -g
```

**Comment by mjm8975** [comment]
I am also getting this error.

**Comment by benstegink** [comment]
I also get the error

**Comment by optixx** [comment]
Having the same issues using git checkout @50d70ce1213567005b106f74c1a33203ab0bdbd9 on osx 10.10 with node v4.2.1

**Comment by ChristopherJoonMiller** [comment]
same
```
Christophers-MacBook-Pro:~ chris$ airsonos
Searching for Sonos devices on network...


/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
                  ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)
Christophers-MacBook-Pro:~ chris$ node -v
v0.12.0
Christophers-MacBook-Pro:~ chris$ npm -v
2.5.1
Christophers-MacBook-Pro:~ chris$ airsonos --version
0.2.4
Christophers-MacBook-Pro:~ chris$ uname -a
Darwin Christophers-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

**Comment by thomascjohnson** [comment]
Me too! :(

**Comment by B1tMaster** [comment]
Me too. same issue. It was working fine until I upgraded Sonos to the latest firmware a few days ago. Not sure if this is related, but this is my impression of causality  here.

**Comment by B1tMaster** [comment]
Yes, I can confirm. My laptop was not updated with new airsonos install for a while and it was also working, but now that fails also. So it is should be related to a firmware upgrade of Sonos.

**Comment by dsarel10** [comment]
Just want to give an update to my situation.  At least in my case, it seems like the Sonos bridge was to blame.

I was able to finally get it to work by removing my bridge and hard wiring one of my Sonos speakers directly through ethernet.  After pulling out the bridge, Airsonos started working flawlessly.

I started this test by unplugging every Sonos speaker (and the bridge) and then ran Airsonos. I obviously didn't find any speakers, but I also didn't get the error.  I then plugged in ONLY the bridge, ran Airsonos again and immediately got the error.

I unplugged the bridge and hard wired one of my Play:1's.  Worked fine.  I then plugged in all the rest of my speakers and it's back to working like it used to.

I'm currently running it on Ubuntu 14.04 with Node 0.12.7.  Hope this helps some of the rest of you.

**Comment by B1tMaster** [comment]
I don't have the bridge, but have the error. So bridge maybe involved, but not the only reason.

**Comment by dsarel10** [comment]
Hmm, so maybe not the bridge per se, but something about the way they're connected?  Sorry I don't have a better suggestion.

**Comment by B1tMaster** [comment]
I suspect it is the latest firmware upgrade from Sonos. Are your speakers up to the latest firmware? I think the latest firmware update had to do with support for more internet radio stations. Which is exactly HOW airsonos works. They added support for more radio stations formats and probably broke the hack airsonos was using.

**Comment by dsarel10** [comment]
Yes, I believe they are running the latest firmware.  My speakers are running "Version: 6.0 (build 31322220)".

I've also encountered another person who says they're running version 6.0, who confirmed that AirSonos was working for them.

All I can say is that unplugging the bridge immediately fixed the problem for me. So something about the way it was reporting back to AirSonos (the formatting, the order...) was causing it to choke.  It may be related to something that changed in version 6.0.

**Comment by B1tMaster** [comment]
Latest firmware is 6.0.1 . Maybe your bridge is on the latest firmware while the speakers are not. Anyway, on Dec 15, we will have Sonos Beta that supports Apple Music. This may mean that this project may never get updated again and official support is coming soon.

**Comment by dsarel10** [comment]
I just updated all the speakers to Version: 6.1 (build 31823140) right now.  Still working for me.  Didn't plug the bridge back in though.

What makes you think official support may be coming?

**Comment by B1tMaster** [comment]
http://blog.sonos.com/news/sonos-welcomes-apple-music/

**Comment by benstegink** [comment]
That's just Apple Music thought, that doesn't accomplish the same thing as airsonos does which is to stream the audio from your computer to the speaker via AirPlay....I don't see the news about Apple Music being anything that removes the need for something like airsonos.

FYI...I'm still getting errors as well, haven't tried unplugging my bridge yet but may give it a shot in the next few days when I have some time to play with it.

**Comment by B1tMaster** [comment]
ben, I was kind of the same opinion at first, just wanting airplay. But after having done some research it seems that AirPlay is really sucky and outdated technology that badly needs revamp. Sonos approach is very solid and their protocol is much more sophisticated . In addition, Airplay require your computer to be on and stream the data from computer to a speaker. Sonos play 5 will instead be playing music directly from AppleMusic server. Once you start the play, you will be able to walk away, turn off your iPhone or iMac and speaker will continue playing. you can leave the house and stop/start speaker and it will re-connect to AppleMusic with your credentials and play. So no middleman in between the speaker and the streaming service. Can you see the advantage. ? So, if they do not make it airplay, I am no longer as concerned as I was before.

**Comment by B1tMaster** [comment]
Here is an opinion on Airplay:  http://9to5mac.com/2015/08/26/opinion-airplay-future/

**Comment by benstegink** [comment]
I agree that if all you want it for is Apple Music the Sonos approach is much better.  I have speakers around the house already and use them with Amazon music.  However, the advantage of airsonos is you can use it for ALL computer sounds.  I'm interested in this project in order to be able to replace my computer speakers with Sonos speakers.  So that ever computer sounds is play through the sonos speaker, not simply music :)  That's why I don't see the Sonos approach as making this project obsolete as there are still people that want a true computer speaker replacement, not just to be able to play Apple Music.

**Comment by paolodenti** [comment]
same problem here

**Comment by fate2001** [comment]
same for me. Sonos 6.1.1 (31824160)
Bridge and Playbar still wired, all other devices are wireless.

**Comment by landerss0n** [comment]
same here..

**Comment by craigtsmith** [comment]
+1

**Comment by xuncia** [comment]
Also for me same problem, it seems that as soon as I added two players 1as surround system, airsonos give me the throw e error.
Any one in the meantime found out a solution?

**Comment by alins** [comment]
no solution yet? i have the same problem

**Comment by xuncia** [comment]
Well, I used a workaround that works fine for me. First you need to check which of your speakers are on WM:0 (sonosnetwork) if you cannot setup them in your network (they must be WM:1) for example in my case when I enable the surrond between the soundbar and two players 1 the two players 1 go directly on WM:0 (sonos network). When you check which speakers are on sonos network you need to switch them off, wait 1 minute and then you can launch airsonos and you can switch on again the speakers that you just switch off, it works perfect.

**Comment by jackrichins** [comment]
All of my devices are WM:0. How do you get them into WM:1? Do you mean I need to disconnect all my bridges to get them off my sonosnetwork?

**Comment by jackrichins** [comment]
Disconnecting all my bridges worked. Guess this means airsonos doesn't work with sonosnetwork, only wifi?

**Comment by jens-maus** [comment]
I also have the same error here after having bought a playbar recently. As soon as I have connected two play:1 devices for surround airsonos stopped working and return the crash report mentioned here. Any help in debugging this situation would be appreciated. Might this be a problem in airsonos or in one of the associated node modules it uses? I still have limited javascript experience but could help in debugging this situation if necessary.

**Comment by B1tMaster** [comment]
Wow, it works now for me! I just did ports self update, followed by upgrade outdated, followed by reinstall of sonos with NPM. to my surprise, it built fine and now I am streaming to all my sonos devices in the house again. I am not sure what changed between 2 days ago and today, but it is now seem to be working. !!

**Comment by B1tMaster** [comment]
An update:

 It stopped working and I was stunned to see an error message I seen before. Then I started looking on what did I do to cause it to fail. And I think I found a potential issue. I invite all others to try and see if you replicate it and if you can fix it the same way I did again. 

What I have done was I reinstalled airsonos and it worked perfectly. To break it again, what I have done was this:  I started the Sonos Controller while running air-sonos. And it could NOT connect to speakers. 
I think airsonos negotiates a different port to connect to speakers. and Sonos Controller was displaying a different port. 

So I killed airsonos. But Sonos controller still could not connect to my speakers.

So I restarted the speakers . that made Sonos controller work. 
I created a new queue on my Play5 with some songs. played for a while
stopped the Sonos controller and tried to start the airsonos again. This is when it started throwing error you see below. 

Then I removed all songs from the QUEUE on a speaker and restarted it. 
And that immediately FIXED the airsonos error and it is Working again. 

My conclusion is that airsonos error below have something to do with an existing music queue on a speaker.  Try to clean up the queues on Sonos speakers before starting airsonos and see if that fixes error below.



Error:
myidko$ airsonos
Searching for Sonos devices on network...


/opt/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
Error: Internal Server Error
    at maybeWrapAsError (/opt/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /opt/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50

**Comment by landerss0n** [comment]
Removing all songs from the queue and exiting sonos controller app worked for me aswell

**Comment by benstegink** [comment]
I emptied my queue and exited the sonos controller app and still no luck for me.  I don't know if it's also something to do with the boost as I have that on my network as well?  Do those of you that have it working also have the Sonos Boost? Or just speakers?

**Comment by landerss0n** [comment]
Im only using the speakers without bridge or boost

**Comment by B1tMaster** [comment]
I have 2 play1, 1 play5, sonos TV bar + subwoofer. 
All latest firmware . 
Also I just upgraded all my MacPorts 
And re-installed airsonos.
Also, for good measure, after you empty the queue and exit sonos controller, restart all speakers.
If that does not help, try without a boost to see if that makes a difference. 

Works like a charm for me now.

**Comment by xuncia** [comment]
If anyone still have the problem I've figure out a little workaround that could help, at least I hope so.
You can use this bash script:
```javascript
#!/usr/bin/bash

# Switch off wifi controller for left Player 1
curl http://airsonos_play1:1400/wifictrl?wifi=off

# Switch off wifi controller for right Player 1
curl http://airsonos_play1(2):1400/wifictrl?wifi=off 


sleep 60

airsonos


# Switch on wifi controller for left Player 1
curl http://airsonos_play1:1400/wifictrl?wifi=on 

# Switch on wifi controller for right Player 1
curl http://airsonos_play1(2):1400/wifictrl?wifi=on 
```

In my case it's the surround system with the two play1 that creates the problem, so I switch off the wifi chip of the two play1 sonos speakers, I wait about 60 seconds (maybe I can wait less let's try) and then  I launch airsonos and switch on the two player1.

**Comment by ady624** [comment]
Found a solution to this. The problem has multiple roots, one being the bridge (**IF YOU RENAMED IT**) or your boost (again, **IF YOU RENAMED IT**). Second problem is airsonos is trying to hook up to speakers that are part of groups, without themselves being the coordinator of said group. The problem comes from the fact that the groupId is no longer the same for all speakers in the group. Go figure... Sonos!

I have modified line 86 in **_/path_to_node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js_** to the following:

`          if (device.coordinator === 'false' || device.name === 'ady624' || device.name === 'BRIDGE' || device.name === 'BOOST') return; // devices to ignore in search`

I have added **_device.coordinator === 'false'_** to make sure airsonos leaves those grouped non-coordinating speakers alone. I also added **_device.name === 'ady624'_** which is the name of my bridge. The code looks for 'BRIDGE' which is the default name. You need to find the name of your own bridge and put it in there. The easy way is to add a **_console.log(device)_** right after line 104:         **_async.forEach(logicalDevices, function(device, done) {_** and that should list the devices that airsonos is trying to initialize. Then use
`curl 'http://<ip goes here>:1400/xml/device_description.xml'`
on each of the devices until you find your bridge in the XML that is returned. Or perhaps you recognize the name you gave it in the list...

Good luck!

**Comment by ady624** [comment]
A more "professional" fix for module sonos 0.7.0 (will not work with other versions)

Here's the full logicalDevice.js file after the changes:

`var async = require('async'),
    Sonos = require('./sonos').Sonos,
    sonosSearch = require('./sonos').search,
    util = require('util'),
    url = require('url'),
    request = require('request');

function LogicalDevice(devices, coordinator, groupId) {
    if (devices.length === 0) {
        throw new Error('Logical device must be initialized with at least one device (' + devices.length + ' given)');
    }

    var coordinatorDevice = coordinator || devices[0];

    Sonos.call(this, coordinatorDevice.host, coordinatorDevice.port);
    var sonosDevices = devices.map(function (device) {
        return new Sonos(device.host, device.post);
    });

    this.devices = sonosDevices;
    this.groupId = groupId;
}

util.inherits(LogicalDevice, Sonos);

LogicalDevice.prototype.initialize = function (cb) {
    async.forEach(this.devices, function (device, done) {
        device.initialize(done);
    }, cb);
};

LogicalDevice.prototype.destroy = function (cb) {
    async.forEach(this.devices, function (device, done) {
        device.destroy(done);
    }, cb);
};

LogicalDevice.prototype.setVolume = function (volume, cb) {
    this.getVolume(function (oldVolume) {

        var diff = volume - oldVolume;

        async.forEach(this.devices, function (device, done) {
            var oldDeviceVolume = device.state.volume;
            var newDeviceVolume = oldDeviceVolume + diff;

            newDeviceVolume = Math.max(newDeviceVolume, 0);
            newDeviceVolume = Math.min(newDeviceVolume, 100);

            device.setVolume(newDeviceVolume, done);

        }, cb);

    }.bind(this));
};

LogicalDevice.prototype.getVolume = function (cb) {

    var sum = 0;

    this.devices.forEach(function (device) {
        sum += device.state.volume || 0;
    });

    cb(sum / this.devices.length);
};

/**
 * Create a Search Instance (emits 'DeviceAvailable' with a found Logical Sonos Component)
 * @param  {Function} Optional 'DeviceAvailable' listener (sonos)
 * @return {Search/EventEmitter Instance}
 */
var search = function (callback) {
    var search = sonosSearch();

    search.once('DeviceAvailable', function (device) {
        device.getTopology(function (err, topology) {
            if (err) callback(err);
            else {

                var devices = topology.zones;
                var groups = {};

                // bucket devices by groupid
                async.forEach(devices, function (device, done) {
                        //if device is not a coordinator, we need to ignore it
                        if (device.coordinator === 'false' || device.name === 'BRIDGE' || device.name === 'BOOST') {
                            done(null);
                        } else {
                            //we need to poll the device to make sure it's not a Bridge or a Boost - we need to filter these devices out
                            request({
                                uri: device.location,
                                method: 'GET',
                            }, function (err, res, body) {
                                //check the response for Sonos BRIDGE or Sonos BOOST
                                if (!err && (body.search('<modelDescription>Sonos BRIDGE</modelDescription>') < 0) && (body.search('<modelDescription>Sonos BOOST</modelDescription>') < 0)) {
                                    //if we pass the filter, go ahead and add the device to the list
                                    if (!groups[device.group]) groups[device.group] = {
                                        members: []
                                    };
                                    var parsedLocation = url.parse(device.location);
                                    var sonosDevice = new Sonos(parsedLocation.hostname, parsedLocation.port);
                                    if (device.coordinator === 'true') groups[device.group].coordinator = sonosDevice;
                                    groups[device.group].members.push(sonosDevice);
                                };
                                done(null);
                            });
                        }
                    },
                    function (err) {
                        //when we're done with all the device filtering, let's initialze all of the logical devices brefore callback
                        var logicalDevices = Object.keys(groups).map(function (groupId) {
                            var group = groups[groupId];
                            return new LogicalDevice(group.members, group.coordinator, groupId);
                        });

                        async.forEach(logicalDevices, function (device, done) {
                            device.initialize(function (err) {
                                if (err) done(err);
                                else {
                                    done(null);
                                }
                            });
                        }, function (err) {
                            if (err) callback(err);
                            else {
                                callback(null, logicalDevices);
                            }
                        });

                    });

            }
        });
    });

    return search;
};

module.exports = LogicalDevice;
module.exports.search = search;`

**Comment by carlpoole** [comment]
@ady624 Thank you for posting this fix. Worked great for me in solving this issue.

**Comment by alansaul** [comment]
Works great thanks @ady624. Nice find.

**Comment by B1tMaster** [comment]
@ady624 Great Fix. It works for me too. My method was working and then not working again.. Your fix did it. Thank you.

**Comment by jens-maus** [comment]
I could also verify that the fix suggested by @ady624 works great. Here I have a PLAYBAR + two PLAY:1 and airsonos was showing this "maybeWrapAsError" Error as soon as I installed the PLAYBAR with the two PLAY:1 devices.

Here I have applied the following change:

```
--- /usr/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js	2016-04-05 10:37:13.000000000 +0200
+++ /usr/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js_org	2016-04-05 10:39:18.407701883 +0200
@@ -83,7 +83,7 @@
         // bucket devices by groupid
         devices.forEach(function(device) {
 
-          if (device.name === 'BRIDGE' || device.name === 'BOOST') return; // devices to ignore in search
+          if (device.coordinator === 'false' || device.name === 'BRIDGE' || device.name === 'BOOST') return; // devices to ignore in search
 
           if (!groups[device.group]) groups[device.group] = { members: [] };
```

So all I had to do is add `device.coordinator === 'false'` to the `logicalDevice.js` file. And then airsonos stopped crashing.

I also tried figuring out how and where to submit a pull request to get this fix integrated, but I actually didn't find the `logicalDevice.js` file in recent `node-sonos` sources on github (not in https://github.com/stephen/node-sonos nor in https://github.com/bencevans/node-sonos).

Perhaps @stephen can come up with an update that fixes this issue at the right places.

**Comment by jens-maus** [comment]
Ok, I finally found the right branch where the fix to logicalDevice.js has to be applied. Let's hope @stephen will merge it as ASAP.

**Comment by xuncia** [comment]
Great! 
I confirm it's working also for me...one playbar and 2 play 1.
Thanks!

**Comment by ady624** [comment]
@jens-maus I want to stress out that people who purchase a bridge or a boost are given the opportunity to change their name during setup. They are initially called BRIDGE and BOOST respectively and the code is setup to avoid those names, but in order to ensure all will "pass" the error, the code needs to be able to identify the boost and the bridge by means other than just the name. The file I uploaded does just that, otherwise, you're fixing it halfway. Or rather, for only those who either don't have a bridge or a boost, or they didn't care to change their default names.

Glad I could help.

**Comment by mjt5282** [comment]
I wanted to just leave a quick comment.  Just as the Bridge and/or Boost can cause the app to fail to start, also the (EOL'd) Sonos Dock being present in the Sonos Network will also cause the app to launch, same error message as above. Once I unplugged my Dock, the app started fine, and has been playing music and running with no errors for over 24 hours ...

**Comment by seanbetts** [comment]
Hi, just trying to apply this fix as I have a Playbar with two Play1s set up and I'm getting the same maybeWrapAsError above. I've tried applying @ady624  file and I've also tried manually updated the logicalDevice.js file manually with @jens-maus changes but I'm still getting the same maybeWrapAsError. Any ideas? Here's the error:

Searching for Sonos devices on network...


/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)

**Comment by mjt5282** [comment]
Unplug all sonos devices that cannot play music (bridge, dock etc) and wait 30 minutes. Would be great to have this work better in a more heterogeneous environment.

**Comment by seanbetts** [comment]
Hi, thanks for your reply. I've tried that and still have the same problem. Any ideas? Thanks

**Comment by lucdetellis** [comment]
(There's a comment with a solution earlier in this thread: https://github.com/stephen/airsonos/issues/216#issuecomment-199882664)

**Comment by seanbetts** [comment]
Hi, thanks for your help. I've tried that solution a few times and still can't get it to work. I've tried manually changing the logicalDevice.js file as described as well as replacing the file with the one shared by @ady624. Any other ideas?

**Comment by ady624** [comment]
@seanbetts There are some devices filtered out by that if statement. Among them, the bridge. I believe there are other devices there too, like the Dock. If you have any non-speaker devices, try and find out their names and try and add them to that if as to exclude them. See if that works?

**Comment by seanbetts** [comment]
Thank you @ady624. I don't have any other non-speaker devices other than the BRIDGE. I'm pretty sure this is still a problem with my 'Living Room' room set up as I have the Soundbar and two Play:1's as surround speakers

**Comment by seanbetts** [comment]
Actually, I've just noticed that I'm getting a different error now - any ideas?:

Searching for Sonos devices on network...


/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
Error: Method Not Allowed
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)

**Comment by lucdetellis** [comment]
@seanbetts I was getting the "Method Not Allowed" error before I switch to Node 0.12.14. After I switched I got the "Internal Server Error" which replacing `logicalDevice.js` fixed.

However, it seems like there's a problem with the Sonos Bridge. Replacing that file did get airsonos working, but I can only control speakers that aren't going through the Bridge. It's weird because the version of airsonos I was using this past summer worked fine.

**Comment by RodrigoViolante** [comment]
@lucdetellis I got fix that error by installing npm install -g bluebird now the issue is that I don't see any sonos in my network.

**Comment by apeeters** [comment]
@ady624 's solution fixes the error in my rather complex Sonos setup, great work!

**Comment by iamontheinet** [comment]
For those still struggling with the original error reported by @bdsousa, adding "_device.coordinator === 'false' ||_" in **_/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js_** as suggested by @ady624 did it for me:

```
if (device.coordinator === 'false' || device.name === 'BRIDGE' || device.name === 'BOOST') return; // devices to ignore in search
```

**Comment by islanderman** [comment]
@ady624's solution works for me.  Thanks so much!

I have one soundbar and two play1 connected with ethernet cable and one amp on wifi.
