### ISSUE TITLE
Can't Run on Windows 10

### ISSUE THREAD

**Issue by atul1201** [stephen/airsonos#225]
After upgrade to Windows 10 I am receiving the following:

C:\Users\Atul\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\n
ode_modules\mdns\lib\dns_sd.js:35
    throw ex;
    ^

Error: The specified procedure could not be found.
C:\Users\Atul\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\n
ode_modules\mdns\build\Release\dns_sd_bindings.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Atul\AppData\Roaming\npm\node_modules\airson
os\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:24:20)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

C:\Users\Atul>

**Comment by hindsc52** [comment]
getting the exact same error on windows 10 here too.

**Comment by Tiger519** [comment]
Same issue. Did either of you find solutions to this?

**Comment by Tiger519** [comment]
In case anyone stumbles upon this old thread, I was able to get rid of the error by switching to node 0.10.33 (had been running node 5). However, the Windows build version is outdated, so it won't actually show up on any ios9, ios10, or ios11 apps. There is a separate issue open requesting an update to the Windows build #245. The speaker WILL show up in iTunes with the current build, but because airsonos supports PCM only, it will play only static. I believe this is still the case with the newer (non-windows) builds, though the Airsonos speaker will show up as an Airplay destination from ios music-playing applications.
