### ISSUE TITLE
How to run AirSonos in Node?

### ISSUE THREAD

**Issue by Geraldf** [stephen/airsonos#234]
I have a question. How do I run AirSonos with nodejs.

After cloning the git locally and running npm install. 
I try to run : **Node index.js** I do get the following error. 
```
geraldf@Geralds-MBP:~/Projects/airsonos$ node index.js
/Users/geraldf/Projects/airsonos/lib/airsonos.js:1
(function (exports, require, module, __filename, __dirname) { let Promise = re
                                                                  ^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/geraldf/Projects/airsonos/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
``` 

Any hint would be helpful. 
thanks

**Comment by stephen** [comment]
https://github.com/stephen/airsonos#development
