### ISSUE TITLE
Error: Internal Server Error at maybeWrapAsError

### ISSUE THREAD

**Issue by leelouch** [stephen/airsonos#239]
OSX 10.11.1 El Capitan

alain-mac:~ afawaz$ uname -a
Darwin alain-mac.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

brew install node
npm install airsonos -g

alain-mac:~ afawaz$ airsonos --version
0.2.5

/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)

**Comment by leelouch** [comment]
more info : 
please note that from time to time the --diagnostics do not provide sonos details , but stuck before or after those details.

alain-mac:~ afawaz$ airsonos --diagnostics
AirSonos Diagnostics
node version	 v4.1.2
operating sys	 darwin (x64)
ip address	 192.168.0.25

Searching for Sonos devices on network...

Device 	{"host":"192.168.0.27","port":1400,"state":{}} (ANVIL)
`- attrs: 	{"CurrentZoneName":"Séjour",
		"CurrentIcon":"x-rincon-roomicon:family",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"31.3-22220",
		"DisplaySoftwareVersion":"6.0",
		"HardwareVersion":"1.8.2.5-2",
		"IPAddress":"192.168.0.27",
		"MACAddress":"XX:XX:XX:XX:XX:10",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E937EF082E01400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.29:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"8",
		"uuid":"RINCON_B8E937EF082E01400",
		"name":"Séjour"},{"group":"RINCON_B8E937EF02EA01400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.15:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"8",
		"uuid":"RINCON_B8E937EF02EA01400",
		"name":"Séjour"},{"group":"RINCON_5CAAFD13AC0501400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.16:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"7",
		"uuid":"RINCON_5CAAFD13AC0501400",
		"name":"Séjour"},{"group":"RINCON_B8E93767521001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.27:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"7",
		"uuid":"RINCON_B8E93767521001400",
		"name":"Séjour"}]


Device 	{"host":"192.168.0.29","port":1400,"state":{}} (ZPS1)
`- attrs: 	{"CurrentZoneName":"Séjour",
		"CurrentIcon":"x-rincon-roomicon:family",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"31.3-22220",
		"DisplaySoftwareVersion":"6.0",
		"HardwareVersion":"1.8.3.7-2",
		"IPAddress":"192.168.0.29",
		"MACAddress":"XX:XX:XX:XX:XX:2E",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E93767521001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.27:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"7",
		"uuid":"RINCON_B8E93767521001400",
		"name":"Séjour"},{"group":"RINCON_B8E937EF02EA01400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.15:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"8",
		"uuid":"RINCON_B8E937EF02EA01400",
		"name":"Séjour"},{"group":"RINCON_5CAAFD13AC0501400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.16:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"7",
		"uuid":"RINCON_5CAAFD13AC0501400",
		"name":"Séjour"},{"group":"RINCON_B8E937EF082E01400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.29:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"8",
		"uuid":"RINCON_B8E937EF082E01400",
		"name":"Séjour"}]


Device 	{"host":"192.168.0.15","port":1400,"state":{}} (ZPS1)
`- attrs: 	{"CurrentZoneName":"Séjour",
		"CurrentIcon":"x-rincon-roomicon:family",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"31.3-22220",
		"DisplaySoftwareVersion":"6.0",
		"HardwareVersion":"1.8.3.7-2",
		"IPAddress":"192.168.0.15",
		"MACAddress":"XX:XX:XX:XX:XX:EA",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E93767521001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.27:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"7",
		"uuid":"RINCON_B8E93767521001400",
		"name":"Séjour"},{"group":"RINCON_B8E937EF082E01400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.29:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"8",
		"uuid":"RINCON_B8E937EF082E01400",
		"name":"Séjour"},{"group":"RINCON_5CAAFD13AC0501400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.16:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"7",
		"uuid":"RINCON_5CAAFD13AC0501400",
		"name":"Séjour"},{"group":"RINCON_B8E937EF02EA01400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.15:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"8",
		"uuid":"RINCON_B8E937EF02EA01400",
		"name":"Séjour"}]


Device 	{"host":"192.168.0.16","port":1400,"state":{}} (ZPS9)
`- attrs: 	{"CurrentZoneName":"Séjour",
		"CurrentIcon":"x-rincon-roomicon:family",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"31.3-22220",
		"DisplaySoftwareVersion":"6.0",
		"HardwareVersion":"1.9.1.10-2",
		"IPAddress":"192.168.0.16",
		"MACAddress":"XX:XX:XX:XX:XX:05",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"2"}
`- topology: 	[{"group":"RINCON_B8E93767521001400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.27:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"7",
		"uuid":"RINCON_B8E93767521001400",
		"name":"Séjour"},{"group":"RINCON_B8E937EF02EA01400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.15:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"8",
		"uuid":"RINCON_B8E937EF02EA01400",
		"name":"Séjour"},{"group":"RINCON_B8E937EF082E01400:2",
		"coordinator":"false",
		"htsat":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"5200",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.29:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"8",
		"uuid":"RINCON_B8E937EF082E01400",
		"name":"Séjour"},{"group":"RINCON_5CAAFD13AC0501400:1",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.0.16:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"7",
		"uuid":"RINCON_5CAAFD13AC0501400",
		"name":"Séjour"}]

**Comment by TigerdyretClaus** [comment]
I have the same issue with exact same versions. It started after I changed the name of two Sonos zones. Before the change all my 8 zones were visible and reachable without problems. Any ideas?

**Comment by ColinRioux** [comment]
I myself am looking for a fix to this issue. I will link if I find one, but if you find one first link me? Thanks.

**Comment by dsarel10** [comment]
Just want to give an update to my situation. At least in my case, it seems like the Sonos bridge was to blame.

I was able to finally get it to work by removing my bridge and hard wiring one of my Sonos speakers directly through ethernet. After pulling out the bridge, Airsonos started working flawlessly.

I started this test by unplugging every Sonos speaker (and the bridge) and then ran Airsonos. I obviously didn't find any speakers, but I also didn't get the error. I then plugged in ONLY the bridge, ran Airsonos again and immediately got the error.

I unplugged the bridge and hard wired one of my Play:1's. Worked fine. I then plugged in all the rest of my speakers and it's back to working like it used to.

I'm currently running it on Ubuntu 14.04 with Node 0.12.7 and Sonos version 6.0. Hope this helps some of the rest of you.

**Comment by TigerdyretClaus** [comment]
Just a status from me.
    
    Thanks for posting below. I tried the same: Stopping all Sonos
    device followed by disconnecting my bridge. I connected my Playbar
    to Ethernet and turned on. Tested airsonos, and continued adding the
    other 6 zones one at a time testing airsonos for each step. (I have
    various configurations of Connect:amp, Play:1, :3 and  old :5 some
    of these in stereo.) This all went well and airsonos worked. 
    
    In the end I also tried to turn my Sub connected to the Playbar on.
    That made airsonos fail when restarted. 
    
    My hypothesis is that we are seeing some sort of topology problem. I
    know that the Sub is using 5 GHz network which then requires some
    bridging from the Sonos generated 2.4 GHz network. I guess the only
    way to know is to make ones own branch of the code on Github and
    start testing. I know nothing of JavaScript, so that will be a steep
    learning curve...
    
    Anyway, I'm using OSX 10.11.1, Node 0.12.7 and of course airsonos
    0.2.5
    
    Den 03/12/2015 kl. 04.20 skrev ds:
    
    
      Just want to give an update to my situation. At least in my
        case, it seems like the Sonos bridge was to blame.
      I was able to finally get it to work by removing my bridge and
        hard wiring one of my Sonos speakers directly through ethernet.
        After pulling out the bridge, Airsonos started working
        flawlessly.
      I started this test by unplugging every Sonos speaker (and the
        bridge) and then ran Airsonos. I obviously didn't find any
        speakers, but I also didn't get the error. I then plugged in
        ONLY the bridge, ran Airsonos again and immediately got the
        error.
      I unplugged the bridge and hard wired one of my Play:1's.
        Worked fine. I then plugged in all the rest of my speakers and
        it's back to working like it used to.
      I'm currently running it on Ubuntu 14.04 with Node 0.12.7 and
        Sonos version 6.0. Hope this helps some of the rest of you.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      Claus Bredahl Rosengaard
      Uldvejen 5, DK2970 Hørsholm
      Telefon: 45 57 20 22, mobil: 50 82 20 22

**Comment by TigerdyretClaus** [comment]
Sure, deal!

Med venlig hilsen
Claus Bredahl Rosengaard

Uldvejen 5, 2970 Hørsholm, Danmark
Tlf. : +45 5082 2022

**Comment by DoesN0tCompute** [comment]
Hello, I was able to confirm this.

1 Playbar
1 Sub
2x Play1

Playbar connected directly via ethernet. I get stuck on "Searching for Sonos." (this is user justintime/airsonos docker container)

If I ungroup everything then all items are detected.  

I will try plugging the sub via ethernet to see if that makes a difference.

**Comment by DoesN0tCompute** [comment]
No good, tried Sub plugged and Playbar Plugged, only Sub plugged, only bridge plugged.  Still not detected unless everything is ungrouped.

**Comment by ianm2k4** [comment]
I think the SonosNet is the problem. I had the system all setup using SonosNet and constantly got that maybeWrapAsError issue. I then set the system up to use my network which I could see it using in the about My Sonos dialog BUT the sub was using SonosNet. I couldnt work out how to make it use the local network without plugging in a cable.

So I turned off the sub and lo and behold airsonos started working. I then plugged the sub back in (it then used the SonosNet again) but airsonos also kept working. It also used the sub when playing through the playbar.

So not a solution but a hack workaround until a solution appears.

**Comment by mikea** [comment]
I'm having this problem and I've investigated it a bit.
I have Bar+2xPlay1 Surround+Sub.

It seems that when airsonos queries all devices, the Sub for some reason reports that it belongs to a different group:

Sub:

behindwifiext: "0"
bootseq: "14"
channelfreq: "5805"
coordinator: "false"
group: "RINCON_B8E937665BBE01400:2"
hasconfiguredssid: "1"
htsat: "true"
legacycompatibleversion: "24.0-00000"
location: "http://192.168.1.11:1400/xml/device_description.xml"
mincompatibleversion: "29.0-00000"
name: "TV Room"
uuid: "RINCON_B8E937665BBE01400"
version: "31.8-24090"
wifienabled: "1"
wirelessmode: "0"

Bar:

behindwifiext: "0"
bootseq: "17"
channelfreq: "2437"
coordinator: "true"
group: "RINCON_B8E9377EF5A301400:71"
hasconfiguredssid: "1"
legacycompatibleversion: "24.0-00000"
location: "http://192.168.1.10:1400/xml/device_description.xml"
mincompatibleversion: "29.0-00000"
name: "TV Room"
uuid: "RINCON_B8E9377EF5A301400"
version: "31.8-24090"
wifienabled: "1"
wirelessmode: "0"


The code creates sonos group for the Sub and then tries to control it. Which obviously doesn't work because Sub is not a controller.

I'll try to fix the issue by filtering out groups without controllers.

**Comment by TigerdyretClaus** [comment]
Thanks for the update!
      That goes well together with the fact that I can start my airsonos
      configuration without errors whenever my sub is turned off. I can
      easily turn it on later, probably because airsonos doesn't perform
      regular scans.
      
      /CBR
    
    Den 23/01/2016 kl. 19:46 skrev Mike
      Aizatsky:
    
    
      I'm having this problem and I've investigated it a bit.
        I have Bar+2xPlay1 Surround+Sub.
      It seems that when airsonos queries all devices, the Sub for
        some reason reports that it belongs to a different group:
      Sub:
      behindwifiext: "0"
        bootseq: "14"
        channelfreq: "5805"
        coordinator: "false"
        group: "RINCON_B8E937665BBE01400:2"
        hasconfiguredssid: "1"
        htsat: "true"
        legacycompatibleversion: "24.0-00000"
        location: "http://192.168.1.11:1400/xml/device_description.xml"
        mincompatibleversion: "29.0-00000"
        name: "TV Room"
        uuid: "RINCON_B8E937665BBE01400"
        version: "31.8-24090"
        wifienabled: "1"
        wirelessmode: "0"
      Bar:
      behindwifiext: "0"
        bootseq: "17"
        channelfreq: "2437"
        coordinator: "true"
        group: "RINCON_B8E9377EF5A301400:71"
        hasconfiguredssid: "1"
        legacycompatibleversion: "24.0-00000"
        location: "http://192.168.1.10:1400/xml/device_description.xml"
        mincompatibleversion: "29.0-00000"
        name: "TV Room"
        uuid: "RINCON_B8E9377EF5A301400"
        version: "31.8-24090"
        wifienabled: "1"
        wirelessmode: "0"
      The code creates sonos group for the Sub and then tries to
        control it. Which obviously doesn't work because Sub is not a
        controller.
      I'll try to fix the issue by filtering out groups without
        controllers.
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
Med venlig hilsen
Claus Bredahl Rosengaard

Uldvejen 5, 2970 Hørsholm, Danmark
Tlf. : +45 5082 2022

**Comment by jens-maus** [comment]
I am having the exact same problem as reported here after I have bought a playbar and connected two play:1 for surround. Please note that I have no Sub at all so for me this isn't really related to the Sub being the reason for that. But as soon as I have connected my two Play:1 devices to the Playbar airsonos stopped working and reports the same problem as mentioned here.

Any hint where to exactly look at the code to potentially fix the problem would be great as I really want to have airsonos back running

**Comment by jackrichins** [comment]
I'm trying to do the same thing. I think the problem is Airsonos searches for all Sonos devices and tries to control them all, even bridges, subs, and surround sound speakers which should be ignored. 

As to where in the code to do this, I'm less certain. It

**Comment by jackrichins** [comment]
I am looking at Airsonos.js as the likely spot in the code, but am not familiar enough with the packages to know how to fix it.

**Comment by xuncia** [comment]
same problem also for me...after I added two play1 as a surround system....the only way is to switch off the two player1, run airsonos and then switch on them again.....

**Comment by xuncia** [comment]
If anyone still have the problem I've figure out a little workaround that could help, at least I hope so.
You can use this bash script:
```javascript
#!/usr/bin/bash

# Switch off wifi controller for left Player 1
curl http://airsonos_play1:1400/wifictrl?wifi=off

# Switch off wifi controller for right Player 1
curl http://airsonos_play1(2):1400/wifictrl?wifi=off 


sleep 60

airsonos


# Switch on wifi controller for left Player 1
curl http://airsonos_play1:1400/wifictrl?wifi=on 

# Switch on wifi controller for right Player 1
curl http://airsonos_play1(2):1400/wifictrl?wifi=on 
```

In my case it's the surround system with the two play1 that creates the problem, so I switch off the wifi chip of the two play1 sonos speakers, I wait about 60 seconds (maybe I can wait less let's try) and then  I launch airsonos and switch on the two player1.

**Comment by jens-maus** [comment]
How can you switch of the WiFi-Controller without losing connection to the two play:1? Do you have them connected to your LAN as well via a ethernet cable?

**Comment by xuncia** [comment]
You can lose control and then when you switch on again the configuration will be there as before.

**Comment by jens-maus** [comment]
But how can you switch it on again if the WiFi of the play:1 devices is off? This is what I don't understand.

**Comment by RustyDust** [comment]
You simply power off the device. It will start with WLAN re-enabled.

**Comment by jens-maus** [comment]
That's clear, but that's not what @xuncia wrote and not what his shell script is showing. There he immediately enabled the WiFi again after having started airsonos. That's why I wonder.

**Comment by RustyDust** [comment]
Ah sorry, I misread that part as "then I launch airsonos and (manually) switch on ...".

**Comment by xuncia** [comment]
Sorry you are right I need to test it a little bit more.

**Comment by TigerdyretClaus** [comment]
It might in fact work if you also wire the Sonos Play1s through Ethernet.

Med venlig hilsen
Claus Bredahl Rosengaard

Uldvejen 5, 2970 Hørsholm, Danmark
Tlf. : +45 5082 2022

**Comment by ady624** [comment]
Found a solution to this. The problem has multiple roots, one being the bridge (**IF YOU RENAMED IT**) or your boost (again, **IF YOU RENAMED IT**). Second problem is airsonos is trying to hook up to speakers that are part of groups, without themselves being the coordinator of said group. The problem comes from the fact that the groupId is no longer the same for all speakers in the group. Go figure... Sonos!

I have modified line 86 in **_/path_to_node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js_** to the following:

`          if (device.coordinator === 'false' || device.name === 'ady624' || device.name === 'BRIDGE' || device.name === 'BOOST') return; // devices to ignore in search`

I have added **_device.coordinator === 'false'_** to make sure airsonos leaves those grouped non-coordinating speakers alone. I also added **_device.name === 'ady624'_** which is the name of my bridge. The code looks for 'BRIDGE' which is the default name. You need to find the name of your own bridge and put it in there. The easy way is to add a **_console.log(device)_** right after line 104:         **_async.forEach(logicalDevices, function(device, done) {_** and that should list the devices that airsonos is trying to initialize. Then use
`curl 'http://<ip goes here>:1400/xml/device_description.xml'`
on each of the devices until you find your bridge in the XML that is returned. Or perhaps you recognize the name you gave it in the list...

Good luck!

**Comment by ady624** [comment]
A more "professional" fix for module sonos referenced above (will not work with other versions).

I am confused as to which version this is, it says I got version 0.12.0 but the package.json says 0.7.0. Besides that, version 0.12.0 does not seem to have a logicalDevice.js file... Make a backup before doing anything.

Here's the full logicalDevice.js file after the changes:

> var async = require('async'),
>     Sonos = require('./sonos').Sonos,
>     sonosSearch = require('./sonos').search,
>     util = require('util'),
>     url = require('url'),
>     request = require('request');
> 
> function LogicalDevice(devices, coordinator, groupId) {
>     if (devices.length === 0) {
>         throw new Error('Logical device must be initialized with at least one device (' + devices.length + ' given)');
>     }
> 
>     var coordinatorDevice = coordinator || devices[0];
> 
>     Sonos.call(this, coordinatorDevice.host, coordinatorDevice.port);
>     var sonosDevices = devices.map(function (device) {
>         return new Sonos(device.host, device.post);
>     });
> 
>     this.devices = sonosDevices;
>     this.groupId = groupId;
> }
> 
> util.inherits(LogicalDevice, Sonos);
> 
> LogicalDevice.prototype.initialize = function (cb) {
>     async.forEach(this.devices, function (device, done) {
>         device.initialize(done);
>     }, cb);
> };
> 
> LogicalDevice.prototype.destroy = function (cb) {
>     async.forEach(this.devices, function (device, done) {
>         device.destroy(done);
>     }, cb);
> };
> 
> LogicalDevice.prototype.setVolume = function (volume, cb) {
>     this.getVolume(function (oldVolume) {
> 
>         var diff = volume - oldVolume;
> 
>         async.forEach(this.devices, function (device, done) {
>             var oldDeviceVolume = device.state.volume;
>             var newDeviceVolume = oldDeviceVolume + diff;
> 
>             newDeviceVolume = Math.max(newDeviceVolume, 0);
>             newDeviceVolume = Math.min(newDeviceVolume, 100);
> 
>             device.setVolume(newDeviceVolume, done);
> 
>         }, cb);
> 
>     }.bind(this));
> };
> 
> LogicalDevice.prototype.getVolume = function (cb) {
> 
>     var sum = 0;
> 
>     this.devices.forEach(function (device) {
>         sum += device.state.volume || 0;
>     });
> 
>     cb(sum / this.devices.length);
> };
> 
> /**
>  * Create a Search Instance (emits 'DeviceAvailable' with a found Logical Sonos Component)
>  * @param  {Function} Optional 'DeviceAvailable' listener (sonos)
>  * @return {Search/EventEmitter Instance}
>  */
> var search = function (callback) {
>     var search = sonosSearch();
> 
>     search.once('DeviceAvailable', function (device) {
>         device.getTopology(function (err, topology) {
>             if (err) callback(err);
>             else {
> 
>                 var devices = topology.zones;
>                 var groups = {};
> 
>                 // bucket devices by groupid
>                 async.forEach(devices, function (device, done) {
>                         //if device is not a coordinator, we need to ignore it
>                         if (device.coordinator === 'false' || device.name === 'BRIDGE' || device.name === 'BOOST') {
>                             done(null);
>                         } else {
>                             //we need to poll the device to make sure it's not a Bridge or a Boost - we need to filter these devices out
>                             request({
>                                 uri: device.location,
>                                 method: 'GET',
>                             }, function (err, res, body) {
>                                 //check the response for Sonos BRIDGE or Sonos BOOST
>                                 if (!err && (body.search('<modelDescription>Sonos BRIDGE</modelDescription>') < 0) && (body.search('<modelDescription>Sonos BOOST</modelDescription>') < 0)) {
>                                     //if we pass the filter, go ahead and add the device to the list
>                                     if (!groups[device.group]) groups[device.group] = {
>                                         members: []
>                                     };
>                                     var parsedLocation = url.parse(device.location);
>                                     var sonosDevice = new Sonos(parsedLocation.hostname, parsedLocation.port);
>                                     if (device.coordinator === 'true') groups[device.group].coordinator = sonosDevice;
>                                     groups[device.group].members.push(sonosDevice);
>                                 };
>                                 done(null);
>                             });
>                         }
>                     },
>                     function (err) {
>                         //when we're done with all the device filtering, let's initialze all of the logical devices brefore callback
>                         var logicalDevices = Object.keys(groups).map(function (groupId) {
>                             var group = groups[groupId];
>                             return new LogicalDevice(group.members, group.coordinator, groupId);
>                         });
> 
>                         async.forEach(logicalDevices, function (device, done) {
>                             device.initialize(function (err) {
>                                 if (err) done(err);
>                                 else {
>                                     done(null);
>                                 }
>                             });
>                         }, function (err) {
>                             if (err) callback(err);
>                             else {
>                                 callback(null, logicalDevices);
>                             }
>                         });
> 
>                     });
> 
>             }
>         });
>     });
> 
>     return search;
> };
> 
> module.exports = LogicalDevice;
> module.exports.search = search;

**Comment by richardtape** [comment]
@ady624 !! Thank you _so_ much! This actually fixes it here, too!!
