### ISSUE TITLE
Unable to build on Debian8

### ISSUE THREAD

**Issue by fate2001** [stephen/airsonos#251]
Hi.
I do have an issue with my Debian System and Airsonos. It tells me, that my current architecture is not supported.
Log attached.
Thanks.
fate

31665 error Linux 3.16.0-4-amd64
31666 error argv "node" "/usr/local/bin/npm" "install" "-g"
31667 error node v0.10.29
31668 error npm  v3.5.2
31669 error path /usr/lib/node_modules/airsonos/bin/index.js
31670 error code ENOENT
31671 error errno 34

[npm-debug.log.txt](https://github.com/stephen/airsonos/files/60987/npm-debug.log.txt)

**Comment by tobiastornros** [comment]
@fate2001 

Update Node.js to 0.12.x or later

**Comment by fate2001** [comment]
Thanks. Now the installation was fine, but I get errors on start:

root@server:/home/user# npm install airsonos -g
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
/usr/bin/airsonos -> /usr/lib/node_modules/airsonos/bin/index.js
/usr/lib
└─┬ airsonos@0.2.5 
  └── sonos@0.7.0  (git://github.com/stephen/node-sonos.git#20d6d6afbf04d065330df6288c3db20234b515ce)

npm WARN optional Skipping failed optional dependency /airsonos/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6


root@server:/home/user# airsonos
module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/airsonos/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/airsonos/node_modules/mdns/lib/mdns.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

Any idea? Thanks.

**Comment by fate2001** [comment]
At the end the build was successful, but I cannot start Airsonso.

```
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Searching for Sonos devices on network...


/usr/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
                  ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/lib/node_modules/airsonos/node_modules/request/request.js:129:22)
```
