### ISSUE TITLE
Stuck on Searching for Sonos (--diagnostics works though)

### ISSUE THREAD

**Issue by mabibby** [stephen/airsonos#252]
Hi,

So i'm on the below.

OSX 11.10.2 (El Capitan)
Node 4.2.3

--configuration detects the equipment but running it without, it just hangs....

XXX:node_modules user$ airsonos --diagnostics
AirSonos Diagnostics
node version	 v4.2.3
operating sys	 darwin (x64)
ip address	 127.94.0.1

Searching for Sonos devices on network...

Device 	{"host":"192.168.1.116","port":1400,"state":{}} (ZPS9)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"31.3-22220",
		"DisplaySoftwareVersion":"6.0",
		"HardwareVersion":"1.9.1.10-2",
		"IPAddress":"192.168.1.116",
		"MACAddress":"XX:XX:XX:XX:XX:2D",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"21"}
`- topology: 	[{"group":"RINCON_5CAAFD1A502D01400:1",
		"coordinator":"true",
		"wirelessmode":"1",
		"hasconfiguredssid":"1",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.116:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"5",
		"uuid":"RINCON_5CAAFD1A502D01400",
		"name":"Living Room"}]

**Comment by ColinRioux** [comment]
Best fix I have for you right now is if you're using a bridge, un plug that and connect the speaker to your router via ethernet.

**Comment by DoesN0tCompute** [comment]
I'm also having the same issue, running.

node version	 v0.10.40
operating sys	 linux (x64)
"DisplaySoftwareVersion":"6.1",
0.2.4

stuck at "Searching for Sonos devices on network..." 

disconnected the bridge and hooked up the playbar directly ethernet.

**Comment by ColinRioux** [comment]
Not sure at this point, will let you know as soon as possible. A good thing to try in the meantime is using node v12.4 and see if that does anything. Also check various open/closed issues for your version of Linux (as linux is a general term) and see if people have had any similar issues and possible solutions. As you can see his issue is Mac OSX, although it has similar framework, it still can have different issues and different problems that persist from different areas.

**Comment by DoesN0tCompute** [comment]
I posted on https://github.com/stephen/airsonos/issues/239

It seems like it has something to do with topology. If I remove all items from my PB+SUB+LS+RS combo then its detected without problems.

I also tried plugging ALL items in using ethernet still no go (without bridge.) 

If there is something that I can test for you please let me know.

**Comment by joshholat** [comment]
Just to provide some more info, I'm also experiencing this with the following on OS X 10.11.2:

```
core - Yes, master?: npm --version
3.3.12
core - Yes, master?: node --version
v5.3.0
core - Yes, master?: airsonos --version
0.2.5
```

`airsonos --diagnostics` outputs the following:

```
core - Yes, master?: airsonos --diagnostics
AirSonos Diagnostics
node version	 v5.3.0
operating sys	 darwin (x64)
ip address	 127.94.0.1

Searching for Sonos devices on network...

Device 	{"host":"10.0.0.15","port":1400,"state":{}} (ZPS3)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"31.3-22220",
		"DisplaySoftwareVersion":"6.0",
		"HardwareVersion":"1.8.1.3-1",
		"IPAddress":"10.0.0.15",
		"MACAddress":"XX:XX:XX:XX:XX:B6",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_5CAAFD5107B601400:1",
		"coordinator":"true",
		"wirelessmode":"1",
		"hasconfiguredssid":"1",
		"channelfreq":"2412",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.0.15:1400/xml/device_description.xml",
		"version":"31.3-22220",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"1",
		"uuid":"RINCON_5CAAFD5107B601400",
		"name":"Living Room"}]
```

**Comment by genebean** [comment]
I'm having a similar issue. I've just tried this out and with node  
- 0.10.28
- 0.12.4
- 4.0.0

With all three the --diagnostics flag shows all my stuff. With the first the program runs without error but never finds my devices. With the last two it throws the following error:

```javascript
node@airsonos:~$ airsonos --verbose
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Searching for Sonos devices on network...


/home/node/.npm-packages/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
Error: Method Not Allowed
    at maybeWrapAsError (/home/node/.npm-packages/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/home/node/.npm-packages/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)
```

Here's the first part of the diagnostics:  

```javascript
airsonos --diagnostics
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
AirSonos Diagnostics
node version	 v4.0.0
operating sys	 linux (x64)
ip address	 192.168.15.69

Searching for Sonos devices on network...
```

**Comment by DoesN0tCompute** [comment]
Hello wondering if there was any headway in figuring out why airsonos does not work with PB/SUB/LS?RS combo.

**Comment by shawnp0wers** [comment]
This is just to add results from experimenting, it also appears for me to be PB/SUB/L/R that breaks things.

**Comment by nazgul** [comment]
I'm having a similar issue. --diagnostics shows both my devices, but without it, I only get a connection to one of them.

```
AirSonos Diagnostics
node version	 v5.5.0
operating sys	 darwin (x64)
ip address	 10.0.201.30

Searching for Sonos devices on network...

Device 	{"host":"10.0.201.4","port":1400,"state":{}} (ZPS1)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"31.8-24090",
		"DisplaySoftwareVersion":"6.1",
		"HardwareVersion":"1.8.3.7-1",
		"IPAddress":"10.0.201.4",
		"MACAddress":"XX:XX:XX:XX:XX:A2",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E9375668A201400:12",
		"coordinator":"false",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.201.32:1400/xml/device_description.xml",
		"version":"31.8-24090",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"34",
		"uuid":"RINCON_B8E93756687201400",
		"name":"Kitchen"},{"group":"RINCON_B8E9375668A201400:12",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.201.4:1400/xml/device_description.xml",
		"version":"31.8-24090",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"32",
		"uuid":"RINCON_B8E9375668A201400",
		"name":"Living Room"}]


Device 	{"host":"10.0.201.32","port":1400,"state":{}} (ZPS1)
`- attrs: 	{"CurrentZoneName":"Kitchen",
		"CurrentIcon":"x-rincon-roomicon:kitchen",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"31.8-24090",
		"DisplaySoftwareVersion":"6.1",
		"HardwareVersion":"1.8.3.7-1",
		"IPAddress":"10.0.201.32",
		"MACAddress":"XX:XX:XX:XX:XX:72",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"OTP: ",
		"HTAudioIn":"0"}
`- topology: 	[{"group":"RINCON_B8E9375668A201400:12",
		"coordinator":"true",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.201.4:1400/xml/device_description.xml",
		"version":"31.8-24090",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"32",
		"uuid":"RINCON_B8E9375668A201400",
		"name":"Living Room"},{"group":"RINCON_B8E9375668A201400:12",
		"coordinator":"false",
		"wirelessmode":"0",
		"hasconfiguredssid":"0",
		"channelfreq":"2437",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://10.0.201.32:1400/xml/device_description.xml",
		"version":"31.8-24090",
		"mincompatibleversion":"29.0-00000",
		"legacycompatibleversion":"24.0-00000",
		"bootseq":"34",
		"uuid":"RINCON_B8E93756687201400",
		"name":"Kitchen"}]
```

```
nazgul@angmar% airsonos --verbose                                                                                     ~
Searching for Sonos devices on network...

  nodetunes:server starting nodetunes server (Living Room (AirSonos)) +0ms
Living Room (@ 10.0.201.4:1400, RINCON_B8E9375668A201400:12)

Search complete. Set up 1 device tunnel.
```

**Comment by warlordpat** [comment]
I am also having this issue where I just get Searching for Sonos devices on network... 
I am running on a Raspberry Pi 2 with a clean install of raspbian jesse that is updated.  
I do have a PB/SUB/L/R in addition to a few single Sonos devices.  

All the devices are on the same WiFi network, and the pi can see the devices.  In fact, if I manually run the search function from the sonos library, it finds all 6 devices on the network.  I am not familiar with node or js for that matter, so I don't really know where to start debugging this.  I just know that the search can find the speakers, but the airsonos is not running properly.  

I am using airsonos 0.2.6

output of diagnostics:
```
sudo airsonos --diagnostics
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
AirSonos Diagnostics
node version     v4.4.5
operating sys    linux (arm)
ip address       192.168.1.123

Searching for Sonos devices on network...
```

output of search:
```
node
> var Sonos = require('sonos');
undefined
> var search = Sonos.search();
undefined
> search
Search {
  foundSonosDevices:
   { '192.168.1.122': Sonos { host: '192.168.1.122', port: 1400, options: [Object] },
     '192.168.1.147': Sonos { host: '192.168.1.147', port: 1400, options: [Object] },
     '192.168.1.116': Sonos { host: '192.168.1.116', port: 1400, options: [Object] },
     '192.168.1.121': Sonos { host: '192.168.1.121', port: 1400, options: [Object] },
     '192.168.1.100': Sonos { host: '192.168.1.100', port: 1400, options: [Object] },
     '192.168.1.114': Sonos { host: '192.168.1.114', port: 1400, options: [Object] } },
  socket:
   Socket {
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [] },
     _events: { message: [Function], error: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _handle:
      UDP {
        fd: 14,
        lookup: [Function: lookup4],
        owner: [Circular],
        onmessage: [Function: onMessage] },
     _receiving: true,
     _bindState: 2,
     type: 'udp4',
     fd: -42,
     _reuseAddr: undefined },
  pollTimer:
   { _called: false,
     _idleTimeout: 10000,
     _idlePrev:
      Timer {
        '0': [Function: listOnTimeout],
        _idleNext: [Circular],
        _idlePrev: [Circular],
        msecs: 10000 },
     _idleNext:
      Timer {
        '0': [Function: listOnTimeout],
        _idleNext: [Circular],
        _idlePrev: [Circular],
        msecs: 10000 },
     _idleStart: 10943,
     _onTimeout: [Function],
     _repeat: null,
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [] } } }
>
```
