### ISSUE TITLE
fails to run: Error: Cannot find module 'babel/polyfill'

### ISSUE THREAD

**Issue by MarkFull** [stephen/airsonos#255]
Need to update for babel 6.

```
$ airsonos

module.js:340
    throw err;
          ^
Error: Cannot find module 'babel/polyfill'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/airsonos/bin/index.js:4:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Similar to this issue:
https://github.com/cloverfield-tools/cf-package/issues/41

**Comment by ColinRioux** [comment]
You can do this yourself and then make a pull request, otherwise, I don't know if @stephen will answer or has a workaround already.

**Comment by stephen** [comment]
@MarkFull can you clarify what the actual breaking change is here, or what setup (i.e. versions of packages installed globally) can reproduce this?
