### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by tdugger** [stephen/airsonos#265]
got this the first day using airsonos on mac OS X 10.11.2 connecting to a PLAY:1.  Played for most of the day fine but then just quit while playing.

(node) warning: possible EventEmitter memory leak detected. 11 clientDisconnected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at NodeTunes.addListener (events.js:240:17)
    at DeviceTunnel.handleClientConnected (/usr/local/lib/node_modules/airsonos/bin/tunnel.js:93:26)
    at emitOne (events.js:78:13)
    at NodeTunes.emit (events.js:170:7)
    at announceParse (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:141:25)
    at announce (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:81:7)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at emitTwo (events.js:88:13)
    at ServerParser.emit (events.js:173:7)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:293:12)
    at writeOrBuffer (_stream_writable.js:279:5)
    at ServerParser.Writable.write (_stream_writable.js:208:11)
    at Socket.ondata (_stream_readable.js:529:20)
    at emitOne (events.js:78:13)

**Comment by tdugger** [comment]
I think this happens after the source is paused for a long period of time.

**Comment by afischer** [comment]
Duplicate of #207
