### ISSUE TITLE
Airsonos Issues

### ISSUE THREAD

**Issue by stumarg** [stephen/airsonos#278]
Installed everything as indicated. Using node 0.10.28. Type Airsonos at command prompt. Get the following:

Searching for Sonos devices on network...

Whole House (@ 10.0.0.250:1400, RINCON_B8E937980B2401400:1)
Master Bedroom (@ 10.0.0.26:1400, RINCON_B8E937E6842001400:1)

All looks good. Select one of the sources and AIrsonos crashes with the following:

/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233
      debug('uncaptured SET_PARAMETER method: %s', req.content.toString().trim());
                                                              ^

TypeError: Cannot read property 'toString' of undefined
    at setParameter (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233:63)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at emitTwo (events.js:87:13)
    at ServerParser.emit (events.js:172:7)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:91:14)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at ServerParser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Any thoughts?

**Comment by liz-miller** [comment]
I'm getting this exact same error as well.

**Comment by liz-miller** [comment]
I installed and updated MacPorts and that fixed the problem (running OS X 10.11.2 El Capitan)

**Comment by stumarg** [comment]
I'll give it a go when I get home
