### ISSUE TITLE
toString of Undefined

### ISSUE THREAD

**Issue by thedamon** [stephen/airsonos#283]
I run airsonos, then select airplay on my phone, then when I play on my phone I get the following error in my console:

```
Search complete. Set up 1 device tunnel.
/Users/l392044/.npm-packages/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233
      debug('uncaptured SET_PARAMETER method: %s', req.content.toString().trim());
                                                              ^

TypeError: Cannot read property 'toString' of undefined
    at setParameter (~/.npm-packages/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233:63)
    at RtspServer.<anonymous> (~/.npm-packages/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at emitTwo (events.js:87:13)
    at ServerParser.emit (events.js:172:7)
    at ServerParser._emitMessage (~/.npm-packages/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (~/.npm-packages/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:91:14)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at ServerParser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by jgoldshlag** [comment]
I'm also getting the same error, am using the latest version (0.2.6).

**Comment by weibel** [comment]
Same here. On 0.10.33 I get
```
/home/pi/.nvm/v0.10.33/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233
      debug('uncaptured SET_PARAMETER method: %s', req.content.toString().trim
                                                               ^
TypeError: Cannot call method 'toString' of undefined
    at setParameter (/home/pi/.nvm/v0.10.33/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233:64)
    at RtspServer.<anonymous> (/home/pi/.nvm/v0.10.33/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at ServerParser.emit (events.js:98:17)
    at ServerParser._emitMessage (/home/pi/.nvm/v0.10.33/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/home/pi/.nvm/v0.10.33/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:91:14)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at ServerParser.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Socket.pipeOnReadable (_stream_readable.js:642:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

Same situation on 0.12.12
```
/home/pi/.nvm/versions/node/v0.12.12/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233
      debug('uncaptured SET_PARAMETER method: %s', req.content.toString().trim
                                                              ^
TypeError: Cannot read property 'toString' of undefined
    at setParameter (/home/pi/.nvm/versions/node/v0.12.12/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233:63)
    at RtspServer.<anonymous> (/home/pi/.nvm/versions/node/v0.12.12/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at ServerParser.emit (events.js:110:17)
    at ServerParser._emitMessage (/home/pi/.nvm/versions/node/v0.12.12/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/home/pi/.nvm/versions/node/v0.12.12/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:91:14)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ServerParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
```

**Comment by weibel** [comment]
It looks like this bug has already been reported at nodetunes. https://github.com/stephen/nodetunes/issues/39

**Comment by ttop** [comment]
Same error here, on my first attempt to use airsonos.

**Comment by thedamon** [comment]
Weirdly, I just uninstalled and reinstalled airsonos and this error went away. Newer versions of some of its dependencies does the trick I think?
