### ISSUE TITLE
warning on memory leak

### ISSUE THREAD

**Issue by jbehr** [stephen/airsonos#285]
airsonos prints warning message from time to time but keeps working:

------

warning: possible EventEmitter memory leak detected. 11 clientDisconnected listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at NodeTunes.addListener (events.js:252:17)
    at DeviceTunnel.handleClientConnected (/usr/local/lib/node_modules/airsonos/bin/tunnel.js:93:26)
    at emitOne (events.js:90:13)
    at NodeTunes.emit (events.js:182:7)
    at announceParse (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:141:25)
    at announce (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:81:7)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at emitTwo (events.js:100:13)
    at ServerParser.emit (events.js:185:7)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at ServerParser.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)

**Comment by afischer** [comment]
Duplicate of #207
