### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ryhart18** [stephen/airsonos#294]
Hi,

Trying to install on 10.10.5, no luck. This is what I am getting:

```
Ryans-Mac-Pro:~ ryan$ npm install airsonos -g
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
/usr/local/bin/airsonos -> /usr/local/lib/node_modules/airsonos/bin/index.js

 mdns@2.3.1 install /usr/local/lib/node_modules/airsonos/node_modules/mdns
 node-gyp rebuild

make: *** No rule to make target `../../../../../../../../Volumes/WD', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/airsonos/node_modules/mdns
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/WD 1TB/Users/ryan/npm-debug.log
npm ERR! code 1
```

This is is the entry in npm-debug.log
[more above here]
```
37602 silly lifecycle esprima@2.7.2~install: no script for install, continuing
37603 silly install nan@2.1.0 /usr/local/lib/node_modules/.staging/nan-76d797c0
37604 info lifecycle nan@2.1.0~install: nan@2.1.0
37605 silly lifecycle nan@2.1.0~install: no script for install, continuing
37606 silly install mdns@2.3.1 /usr/local/lib/node_modules/.staging/mdns-91640236
37607 info lifecycle mdns@2.3.1~install: mdns@2.3.1
37608 verbose lifecycle mdns@2.3.1~install: unsafe-perm in lifecycle true
37609 verbose lifecycle mdns@2.3.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/airsonos/node_modules/mdns/node_modules/.bin:/usr/local/lib/node_modules/airsonos/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
37610 verbose lifecycle mdns@2.3.1~install: CWD: /usr/local/lib/node_modules/airsonos/node_modules/mdns
37611 silly lifecycle mdns@2.3.1~install: Args: [ '-c', 'node-gyp rebuild' ]
37612 silly lifecycle mdns@2.3.1~install: Returned: code: 1  signal: null
37613 info lifecycle mdns@2.3.1~install: Failed to exec install script
37614 verbose unlock done using /Volumes/WD 1TB/Users/ryan/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
37615 silly rollbackFailedOptional Starting
37616 silly rollbackFailedOptional Finishing
37617 silly runTopLevelLifecycles Starting
37618 silly runTopLevelLifecycles Finishing
37619 silly install printInstalled
37620 verbose stack Error: mdns@2.3.1 install: `node-gyp rebuild`
37620 verbose stack Exit status 1
37620 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
37620 verbose stack     at emitTwo (events.js:106:13)
37620 verbose stack     at EventEmitter.emit (events.js:191:7)
37620 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
37620 verbose stack     at emitTwo (events.js:106:13)
37620 verbose stack     at ChildProcess.emit (events.js:191:7)
37620 verbose stack     at maybeClose (internal/child_process.js:850:16)
37620 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
37621 verbose pkgid mdns@2.3.1
37622 verbose cwd /Volumes/WD 1TB/Users/ryan
```

Can anyone assist with this?

**Comment by hart1994** [comment]
Looks like this is strictly for node.js 0.10.X. Downgraded and now it's connecting, just a 4-5 second delay.
