### ISSUE TITLE
AirSonos on Mac with latest OS

### ISSUE THREAD

**Issue by erikproper** [stephen/airsonos#300]
Installed AirSonos on my Mac, but when running it I run into the issue below ...

-------
Searching for Sonos devices on network...

/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
            ^
Error: Method Not Allowed
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/request/request.js:129:22)

**Comment by MatthewThornton** [comment]
I'm seeing this as well. Maybe the sonos fork needs to be refreshed from upstream?

**Comment by lucdetellis** [comment]
+1, same issue

**Comment by SnarkNerd** [comment]
> 1. Download: https://github.com/stephen/airsonos/files/184595/logicalDevice.zip
> 2. Replace this file with the file in the link above:
> /path_to_node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js

Am I crazy (or dumb)? I don't have an /airsonos/node_modules/sonos/ folder ... all that's in there is "install" ...
