### ISSUE TITLE
Airsonos crashes on Debian 7.9, NodeJS 0.10.28

### ISSUE THREAD

**Issue by jelimoore** [stephen/airsonos#301]
Hello,
I can open Airsonos, it can search for devices, sets up a tunnel, and I can connect to it. However, when I try  To play music, it throws this in the command line:

/home/jelimoore/.nvm/v0.10.28/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233
      debug('uncaptured SET_PARAMETER method: %s', req.content.toString().trim
                                                               ^
TypeError: Cannot call method 'toString' of undefined
    at setParameter (/home/jelimoore/.nvm/v0.10.28/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233:64)
    at RtspServer.<anonymous> (/home/jelimoore/.nvm/v0.10.28/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at ServerParser.EventEmitter.emit (events.js:98:17)
    at ServerParser._emitMessage (/home/jelimoore/.nvm/v0.10.28/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/home/jelimoore/.nvm/v0.10.28/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:91:14)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at ServerParser.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:582:24)
    at flow (_stream_readable.js:591:7)
    at Socket.pipeOnReadable (_stream_readable.js:623:5)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    at emitReadable (_stream_readable.js:403:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)

Thanks!

**Comment by Jaharmi** [comment]
This looks like the error I am getting on Ubuntu Server. I'm not able to check on it but I remember the TypeError 'toString' line in the output. I happened only after I tried to send audio through Airsonos.

**Comment by jelimoore** [comment]
Exactly same issue I had - only when I play music.
