### ISSUE TITLE
crypto.js crash starting streaming from iOS device

### ISSUE THREAD

**Issue by tedd4u** [stephen/airsonos#302]
Startup and search works fine - it finds the Sonos (Play 1).

But when I start streaming, it crashes immediately with this exception from crypto.js:

> imac:airsonos millers$ airsonos 
> Searching for Sonos devices on network...
> 
> Kitchen (@ 10.0.1.38:1400, RINCON_5CAAFD43B79001400:1)
> 
> Search complete. Set up 1 device tunnel.
> crypto.js:232
>   this._handle.initiv(cipher, toBuf(key), toBuf(iv));
>                ^
> 
> Error: Invalid key length
>     at Error (native)
>     at new Decipheriv (crypto.js:232:16)
>     at Object.Decipheriv (crypto.js:229:12)
>     at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
>     at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
>     at emitTwo (events.js:106:13)
>     at Socket.emit (events.js:191:7)
>     at UDP.onMessage (dgram.js:532:8)

OS version:

> imac:airsonos millers$ uname -a
> Darwin imac.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

Node version:

> imac:airsonos millers$ node --version
> v6.2.0

Package versions:

> imac:airsonos millers$ npm ls
> airsonos@0.2.6 /Users/millers/dev/airsonos
> ├─┬ babel@5.8.38
> │ ├─┬ babel-core@5.8.38
> │ │ ├── babel-plugin-constant-folding@1.0.1
> │ │ ├── babel-plugin-dead-code-elimination@1.0.2
> │ │ ├── babel-plugin-eval@1.0.1
> │ │ ├── babel-plugin-inline-environment-variables@1.0.1
> │ │ ├── babel-plugin-jscript@1.0.4
> │ │ ├── babel-plugin-member-expression-literals@1.0.1
> │ │ ├── babel-plugin-property-literals@1.0.1
> │ │ ├── babel-plugin-proto-to-assign@1.0.4
> │ │ ├── babel-plugin-react-constant-elements@1.0.3
> │ │ ├── babel-plugin-react-display-name@1.0.3
> │ │ ├── babel-plugin-remove-console@1.0.1
> │ │ ├── babel-plugin-remove-debugger@1.0.1
> │ │ ├── babel-plugin-runtime@1.0.7
> │ │ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
> │ │ │ └── leven@1.0.2
> │ │ ├── babel-plugin-undefined-to-void@1.1.6
> │ │ ├── babylon@5.8.38
> ?? bluebird@2.10.2
> │ │ ├─┬ chalk@1.1.3
> │ │ │ ├── ansi-styles@2.2.1
> │ │ │ ├── escape-string-regexp@1.0.5
> │ │ │ ├─┬ has-ansi@2.0.0
> │ │ │ │ └── ansi-regex@2.0.0
> │ │ │ ├── strip-ansi@3.0.1
> │ │ │ └── supports-color@2.0.0
> │ │ ├── core-js@1.2.6
> │ │ ├─┬ detect-indent@3.0.1
> │ │ │ └── get-stdin@4.0.1
> │ │ ├── esutils@2.0.2
> │ │ ├── globals@6.4.1
> │ │ ├─┬ home-or-tmp@1.0.0
> │ │ │ ├── os-tmpdir@1.0.1
> │ │ │ └── user-home@1.1.1
> │ │ ├─┬ is-integer@1.0.6
> │ │ │ └─┬ is-finite@1.0.1
> │ │ │   └── number-is-nan@1.0.0
> │ │ ├── js-tokens@1.0.1
> │ │ ├── json5@0.4.0
> │ │ ├─┬ minimatch@2.0.10
> │ │ │ └─┬ brace-expansion@1.1.4
> │ │ │   ├── balanced-match@0.4.1
> │ │ │   └── concat-map@0.0.1
> │ │ ├── private@0.1.6
> │ │ ├─┬ regenerator@0.8.40
> │ │ │ ├─┬ commoner@0.10.4
> │ │ │ │ ├─┬ detective@4.3.1
> │ │ │ │ │ ├── acorn@1.2.2
> │ │ │ │ │ └── defined@1.0.0
> │ │ │ │ ├── iconv-lite@0.4.13
> │ │ │ │ └── q@1.4.1
> │ │ │ ├─┬ defs@1.1.1
> │ │ │ │ ├─┬ alter@0.2.0
> │ │ │ │ │ └── stable@0.1.5
> │ │ │ │ ├── ast-traverse@0.1.1
> │ │ │ │ ├── breakable@1.0.0
> │ │ │ │ ├── simple-fmt@0.1.0
> │ │ │ │ ├── simple-is@0.2.0
> │ │ │ │ ├── stringmap@0.2.2
> │ │ │ │ ├── stringset@0.2.1
> │ │ │ │ ├── tryor@0.1.2
> │ │ │ │ └─┬ yargs@3.27.0
> │ │ │ │   ├── camelcase@1.2.1
> │ │ │ │   ├─┬ cliui@2.1.0
> │ │ │ │   │ ├─┬ center-align@0.1.3
> │ │ │ │   │ │ ├─┬ align-text@0.1.4
> │ │ │ │   │ │ │ └── longest@1.0.1
> │ │ │ │   │ │ └── lazy-cache@1.0.4
> │ │ │ │   │ └── right-align@0.1.3
> │ │ │ │   ├── decamelize@1.2.0
> │ │ │ │   ├─┬ os-locale@1.4.0
> │ │ │ │   │ └─┬ lcid@1.0.0
> │ │ │ │   │   └── invert-kv@1.0.0
> │ │ │ │   ├── window-size@0.1.4
> │ │ │ │   └── y18n@3.2.1
> │ │ │ ├── esprima-fb@15001.1001.0-dev-harmony-fb
> │ │ │ ├─┬ recast@0.10.33
> │ │ │ │ └── ast-types@0.8.12
> │ │ │ └── through@2.3.8
> │ │ ├─┬ regexpu@1.3.0
> │ │ │ ├── esprima@2.7.2
> │ │ │ ├── regenerate@1.3.1
> │ │ │ ├── regjsgen@0.2.0
> │ │ │ └─┬ regjsparser@0.1.5
> │ │ │   └── jsesc@0.5.0
> │ │ ├── repeating@1.1.3
> │ │ ├── resolve@1.1.7
> │ │ ├── shebang-regex@1.0.0
> │ │ ├─┬ source-map-support@0.2.10
> │ │ │ └─┬ source-map@0.1.32
> │ │ │   └── amdefine@1.0.0
> │ │ ├── to-fast-properties@1.0.2
> │ │ ├── trim-right@1.0.1
> │ │ └── try-resolve@1.0.1
> │ ├─┬ chokidar@1.5.1
> │ │ ├─┬ anymatch@1.3.0
> │ │ │ ├── arrify@1.0.1
> │ │ │ └─┬ micromatch@2.3.8
> │ │ │   ├─┬ arr-diff@2.0.0
> │ │ │   │ └── arr-flatten@1.0.1
> │ │ │   ├── array-unique@0.2.1
> │ │ │   ├─┬ braces@1.8.5
> │ │ │   │ ├─┬ expand-range@1.8.2
> │ │ │   │ │ └─┬ fill-range@2.2.3
> │ │ │   │ │   ├── is-number@2.1.0
> │ │ │   │ │   ├── isobject@2.1.0
> │ │ │   │ │   ├── randomatic@1.1.5
> │ │ │   │ │   └── repeat-string@1.5.4
> │ │ │   │ ├── preserve@0.2.0
> │ │ │   │ └── repeat-element@1.1.2
> │ │ │   ├─┬ expand-brackets@0.1.5
> │ │ │   │ └── is-posix-bracket@0.1.1
> │ │ │   ├── extglob@0.3.2
> │ │ │   ├── filename-regex@2.0.0
> │ │ │   ├─┬ kind-of@3.0.3
> │ │ │   │ └── is-buffer@1.1.3
> │ │ │   ├── normalize-path@2.0.1
> │ │ │   ├─┬ object.omit@2.0.0
> │ │ │   │ ├─┬ for-own@0.1.4
> │ │ │   │ │ └── for-in@0.1.5
> │ │ │   │ └── is-extendable@0.1.1
> │ │ │   ├─┬ parse-glob@3.0.4
> │ │ │   │ ├── glob-base@0.3.0
> │ │ │   │ └── is-dotfile@1.0.2
> │ │ │   └─┬ regex-cache@0.4.3
> │ │ │     ├── is-equal-shallow@0.1.3
> │ │ │     └── is-primitive@2.0.0
> │ │ ├── async-each@1.0.0
> │ │ ├─┬ fsevents@1.0.12
> │ │ │ └─┬ node-pre-gyp@0.6.25
> │ │ │   ├─┬ mkdirp@0.5.1
> │ │ │   │ └── minimist@0.0.8
> │ │ │   ├─┬ nopt@3.0.6
> │ │ │   │ └── abbrev@1.0.7
> │ │ │   ├─┬ npmlog@2.0.3
> │ │ │   │ ├── ansi@0.3.1
> │ │ │   │ ├─┬ are-we-there-yet@1.1.2
> │ │ │   │ │ └── delegates@1.0.0
> │ │ │   │ └─┬ gauge@1.2.7
> │ │ │   │   ├── has-unicode@2.0.0
> │ │ │   │   ├─┬ lodash.pad@4.1.0
> │ │ │   │   │ ├── lodash.repeat@4.0.0
> │ │ │   │   │ └── lodash.tostring@4.1.2
> │ │ │   │   ├── lodash.padend@4.2.0
> │ │ │   │   └── lodash.padstart@4.2.0
> │ │ │   ├─┬ rc@1.1.6
> │ │ │   │ ├── deep-extend@0.4.1
> │ │ │   │ ├── ini@1.3.4
> │ │ │   │ ├── minimist@1.2.0
> │ │ │   │ └── strip-json-comments@1.0.4
> │ │ │   ├─┬ request@2.69.0
> │ │ │   │ ├── aws-sign2@0.6.0
> │ │ │   │ ├─┬ aws4@1.3.2
> │ │ │   │ │ └─┬ lru-cache@4.0.1
> │ │ │   │ │   ├── pseudomap@1.0.2
> │ │ │   │ │   └── yallist@2.0.0
> │ │ │   │ ├── bl@1.0.3
> │ │ │   │ ├── caseless@0.11.0
> │ │ │   │ ├─┬ combined-stream@1.0.5
> │ │ │   │ │ └── delayed-stream@1.0.0
> │ │ │   │ ├── extend@3.0.0
> │ │ │   │ ├── forever-agent@0.6.1
> │ │ │   │ ├─┬ form-data@1.0.0-rc4
> │ │ │   │ │ └── async@1.5.2
> │ │ │   │ ├─┬ har-validator@2.0.6
> │ │ │   │ │ ├─┬ chalk@1.1.3
> │ │ │   │ │ │ ├── ansi-styles@2.2.1
> │ │ │   │ │ │ ├── escape-string-regexp@1.0.5
> │ │ │   │ │ │ ├─┬ has-ansi@2.0.0
> │ │ │   │ │ │ │ └── ansi-regex@2.0.0
> │ │ │   │ │ │ ├── strip-ansi@3.0.1
> │ │ │   │ │ │ └── supports-color@2.0.0
> │ │ │   │ │ ├─┬ commander@2.9.0
> │ │ │   │ │ │ └── graceful-readlink@1.0.1
> │ │ │   │ │ ├─┬ is-my-json-valid@2.13.1
> │ │ │   │ │ │ ├── generate-function@2.0.0
> │ │ │   │ │ │ ├─┬ generate-object-property@1.2.0
> │ │ │   │ │ │ │ └── is-property@1.0.2
> │ │ │   │ │ │ ├── jsonpointer@2.0.0
> │ │ │   │ │ │ └── xtend@4.0.1
> │ │ │   │ │ └─┬ pinkie-promise@2.0.0
> │ │ │   │ │   └── pinkie@2.0.4
> │ │ │   │ ├─┬ hawk@3.1.3
> │ │ │   │ │ ├── boom@2.10.1
> │ │ │   │ │ ├── cryptiles@2.0.5
> │ │ │   │ │ ├── hoek@2.16.3
> │ │ │   │ │ └── sntp@1.0.9
> │ │ │   │ ├─┬ http-signature@1.1.1
> │ │ │   │ │ ├── assert-plus@0.2.0
> │ │ │   │ │ ├─┬ jsprim@1.2.2
> │ │ │   │ │ │ ├── extsprintf@1.0.2
> │ │ │   │ │ │ ├── json-schema@0.2.2
> │ │ │   │ │ │ └── verror@1.3.6
> │ │ │   │ │ └─┬ sshpk@1.7.4
> │ │ │   │ │   ├── asn1@0.2.3
> │ │ │   │ │   ├─┬ dashdash@1.13.0
> │ │ │   │ │   │ └── assert-plus@1.0.0
> │ │ │   │ │   ├── ecc-jsbn@0.1.1
> │ │ │   │ │   ├── jodid25519@1.0.2
> │ │ │   │ │   ├── jsbn@0.1.0
> │ │ │   │ │   └── tweetnacl@0.14.3
> │ │ │   │ ├── is-typedarray@1.0.0
> │ │ │   │ ├── isstream@0.1.2
> │ │ │   │ ├── json-stringify-safe@5.0.1
> │ │ │   │ ├─┬ mime-types@2.1.10
> │ │ │   │ │ └── mime-db@1.22.0
> │ │ │   │ ├── node-uuid@1.4.7
> │ │ │   │ ├── oauth-sign@0.8.1
> │ │ │   │ ├── qs@6.0.2
> │ │ │   │ ├── stringstream@0.0.5
> │ │ │   │ ├── tough-cookie@2.2.2
> │ │ │   │ └── tunnel-agent@0.4.2
> │ │ │   ├─┬ rimraf@2.5.2
> │ │ │   │ └─┬ glob@7.0.3
> │ │ │   │   ├─┬ inflight@1.0.4
> │ │ │   │   │ └── wrappy@1.0.1
> │ │ │   │   ├── inherits@2.0.1
> │ │ │   │   ├─┬ minimatch@3.0.0
> │ │ │   │   │ └─┬ brace-expansion@1.1.3
> │ │ │   │   │   ├── balanced-match@0.3.0
> │ │ │   │   │   └── concat-map@0.0.1
> │ │ │   │   ├─┬ once@1.3.3
> │ │ │   │   │ └── wrappy@1.0.1
> │ │ │   │   └── path-is-absolute@1.0.0
> │ │ │   ├── semver@5.1.0
> │ │ │   ├─┬ tar@2.2.1
> │ │ │   │ ├── block-stream@0.0.8
> │ │ │   │ ├─┬ fstream@1.0.8
> │ │ │   │ │ └── graceful-fs@4.1.3
> │ │ │   │ └── inherits@2.0.1
> │ │ │   └─┬ tar-pack@3.1.3
> │ │ │     ├─┬ debug@2.2.0
> │ │ │     │ └── ms@0.7.1
> │ │ │     ├─┬ fstream-ignore@1.0.3
> │ │ │     │ └─┬ minimatch@3.0.0
> │ │ │     │   └─┬ brace-expansion@1.1.3
> │ │ │     │     ├── balanced-match@0.3.0
> │ │ │     │     └── concat-map@0.0.1
> │ │ │     ├─┬ once@1.3.3
> │ │ │     │ └── wrappy@1.0.1
> │ │ │     ├─┬ readable-stream@2.0.6
> │ │ │     │ ├── core-util-is@1.0.2
> │ │ │     │ ├── isarray@1.0.0
> │ │ │     │ ├── process-nextick-args@1.0.6
> │ │ │     │ ├── string_decoder@0.10.31
> │ │ │     │ └── util-deprecate@1.0.2
> │ │ │     └── uid-number@0.0.6
> │ │ ├── glob-parent@2.0.0
> │ │ ├── inherits@2.0.1
> │ │ ├─┬ is-binary-path@1.0.1
> │ │ │ └── binary-extensions@1.4.1
> │ │ ├─┬ is-glob@2.0.1
> │ │ │ └── is-extglob@1.0.0
> │ │ └─┬ readdirp@2.0.0
> │ │   └── graceful-fs@4.1.4
> │ ├─┬ commander@2.9.0
> │ │ └── graceful-readlink@1.0.1
> │ ├── convert-source-map@1.2.0
> │ ├── fs-readdir-recursive@0.1.2
> │ ├─┬ glob@5.0.15
> │ │ ├─┬ inflight@1.0.5
> │ │ │ └── wrappy@1.0.2
> │ │ └── once@1.3.3
> │ ├── lodash@3.10.1
> │ ├─┬ output-file-sync@1.1.1
> │ │ ├─┬ mkdirp@0.5.1
> │ │ │ └── minimist@0.0.8
> │ │ └── xtend@4.0.1
> │ ├── path-exists@1.0.0
> │ ├── path-is-absolute@1.0.0
> │ ├── slash@1.0.0
> │ └── source-map@0.5.6
> ├── bluebird@2.10.2
> ├── flags@0.1.3
> ├── ip@1.1.0
> ├─┬ nicercast@0.1.0
> │ ├─┬ express@3.5.3
> │ │ ├── buffer-crc32@0.2.1
> │ │ ├─┬ commander@1.3.2
> │ │ │ └── keypress@0.1.0
> │ │ ├─┬ connect@2.14.5
> │ │ │ ├── basic-auth-connect@1.0.0
> │ │ │ ├── bytes@0.3.0
> │ │ │ ├─┬ compression@1.0.0
> │ │ │ │ ├── bytes@0.2.1
> │ │ │ │ ├── compressible@1.0.0
> │ │ │ │ └── negotiator@0.3.0
> │ │ │ ├── connect-timeout@1.0.0
> │ │ │ ├─┬ cookie-parser@1.0.1
> │ │ │ │ └── cookie@0.1.0
> │ │ │ ├─┬ csurf@1.1.0
> │ │ │ │ ├── scmp@0.0.3
> │ │ │ │ └── uid2@0.0.3
> │ │ │ ├── debug@0.8.1
> │ │ │ ├── errorhandler@1.0.0
> │ │ │ ├─┬ express-session@1.0.2
> │ │ │ │ ├── cookie@0.1.0
> │ │ │ │ ├── debug@0.7.4
> │ │ │ │ └── utils-merge@1.0.0
> │ │ │ ├── method-override@1.0.0
> │ │ │ ├─┬ morgan@1.0.0
> │ │ │ │ └── bytes@0.2.1
> │ │ │ ├─┬ multiparty@2.2.0
> │ │ │ │ ├─┬ readable-stream@1.1.14
> │ │ │ │ │ └── isarray@0.0.1
> │ │ │ │ └─┬ stream-counter@0.2.0
> │ │ │ │   └─┬ readable-stream@1.1.14
> │ │ │ │     └── isarray@0.0.1
> │ │ │ ├── pause@0.0.1
> │ │ │ ├── raw-body@1.1.4
> │ │ │ ├── response-time@1.0.0
> │ │ │ ├─┬ serve-index@1.0.1
> │ │ │ │ ├── batch@0.5.0
> │ │ │ │ └── negotiator@0.4.2
> │ │ │ ├─┬ serve-static@1.1.0
> │ │ │ │ └── parseurl@1.0.1
> │ │ │ ├── setimmediate@1.0.1
> │ │ │ ├── static-favicon@1.0.2
> │ │ │ └── vhost@1.0.0
> │ │ ├── cookie@0.1.2
> │ │ ├── cookie-signature@1.0.3
> │ │ ├── debug@0.8.1
> │ │ ├── fresh@0.2.2
> │ │ ├── merge-descriptors@0.0.2
> │ │ ├── methods@0.1.0
> │ │ ├── mkdirp@0.4.0
> │ │ ├── range-parser@1.0.0
> │ │ └─┬ send@0.3.0
> │ │   └── debug@0.8.0
> │ ├─┬ icecast-stack@0.3.0
> │ │ ├─┬ http-stack@0.1.3
> │ │ │ └─┬ header-stack@0.1.3
> │ │ │   ├── bufferjs@2.0.0
> │ │ │   └── bufferlist@0.1.0
> │ │ └── stream-stack@1.1.4
> │ ├── ip@0.3.3
> │ └─┬ lame@1.2.3
> │   ├── bindings@1.2.1
> │   ├── nan@2.3.5
> │   └─┬ readable-stream@1.1.14
> │     └── isarray@0.0.1
> ├─┬ nodetunes@0.3.0
> │ ├─┬ alac2pcm@1.1.0
> │ │ ├── libalac@0.1.2
> │ │ └── minimist@1.2.0
> │ ├─┬ debug@2.2.0
> │ │ └── ms@0.7.1
> │ ├─┬ forge@2.3.0
> │ │ ├── fu@0.1.0
> │ │ ├─┬ jshintify@0.1.0
> │ │ │ └─┬ jshint@2.9.2
> │ │ │   ├─┬ cli@0.6.6
> │ │ │   │ └─┬ glob@3.2.11
> │ │ │   │   └─┬ minimatch@0.3.0
> │ │ │   │     ├── lru-cache@2.7.3
> │ │ │   │     └── sigmund@1.0.1
> │ │ │   ├─┬ console-browserify@1.1.0
> │ │ │   │ └── date-now@0.1.4
> │ │ │   ├── exit@0.1.2
> │ │ │   ├─┬ htmlparser2@3.8.3
> │ │ │   │ ├── domelementtype@1.3.0
> │ │ │   │ ├── domhandler@2.3.0
> │ │ │   │ ├─┬ domutils@1.5.1
> │ │ │   │ │ └─┬ dom-serializer@0.1.0
> │ │ │   │ │   ├── domelementtype@1.1.3
> │ │ │   │ │   └── entities@1.1.1
> │ │ │   │ ├── entities@1.0.0
> │ │ │   │ └─┬ readable-stream@1.1.14
> │ │ │   │   └── isarray@0.0.1
> │ │ │   ├── lodash@3.7.0
> │ │ │   ├── shelljs@0.3.0
> │ │ │   └── strip-json-comments@1.0.4
> │ │ ├─┬ mangleify@0.1.0
> │ │ │ ├─┬ escodegen@1.8.0
> │ │ │ │ ├── esprima@2.7.2
> │ │ │ │ ├── estraverse@1.9.3
> │ │ │ │ ├─┬ optionator@0.8.1
> │ │ │ │ │ ├── deep-is@0.1.3
> │ │ │ │ │ ├── fast-levenshtein@1.1.3
> │ │ │ │ │ ├── levn@0.3.0
> │ │ │ │ │ ├── prelude-ls@1.1.2
> │ │ │ │ │ ├── type-check@0.3.2
> │ │ │ │ │ └── wordwrap@1.0.0
> │ │ │ │ └── source-map@0.2.0
> │ │ │ ├─┬ esmangle@1.0.1
> │ │ │ │ ├── escodegen@1.3.3
> │ │ │ │ ├─┬ escope@1.0.3
> │ │ │ │ │ └── estraverse@2.0.0
> │ │ │ │ ├── esprima@1.1.1
> │ │ │ │ ├─┬ esshorten@1.1.1
> │ │ │ │ │ └── estraverse@4.1.1
> │ │ │ │ ├── estraverse@1.5.1
> │ │ │ │ ├── esutils@1.0.0
> │ │ │ │ ├─┬ optionator@0.3.0
> │ │ │ │ │ ├── fast-levenshtein@1.0.7
> │ │ │ │ │ ├── levn@0.2.5
> │ │ │ │ │ └── wordwrap@0.0.2
> │ │ │ │ └── source-map@0.1.43
> │ │ │ └── esprima@2.7.2
> │ │ ├─┬ reactify@1.1.1
> │ │ │ └─┬ react-tools@0.13.3
> │ │ │   └─┬ jstransform@10.1.0
> │ │ │     ├── base62@0.1.1
> │ │ │     ├── esprima-fb@13001.1001.0-dev-harmony-fb
> │ │ │     └── source-map@0.1.31
> │ │ └── subarg@1.0.0
> │ ├── httplike@1.0.2
> │ ├── ipaddr.js@1.1.1
> │ ├── mdns@2.3.3
> │ ├── metricstream@0.0.0
> │ ├── node-forge@0.6.39
> │ ├─┬ portastic@0.0.1
> │ │ ├── async@0.1.22
> │ │ ├── coffee-script@1.3.3
> │ │ └── commander@1.0.5
> │ ├── priorityqueuejs@0.2.0
> │ ├── random-mac@0.0.4
> │ ├── randomstring@1.0.3
> │ └─┬ readable-stream@2.1.4
> │   ├── buffer-shims@1.0.0
> │   ├── core-util-is@1.0.2
> │   ├── isarray@1.0.0
> │   ├── process-nextick-args@1.0.7
> │   ├── string_decoder@0.10.31
> │   └── util-deprecate@1.0.2
> └─┬ sonos@0.7.0 (git://github.com/stephen/node-sonos.git#20d6d6afbf04d065330df6288c3db20234b515ce)
>   ├── async@0.9.2
>   ├── debug@0.7.4
>   ├── ip@0.3.3
>   ├─┬ request@2.27.0
>   │ ├── aws-sign@0.3.0
>   │ ├── cookie-jar@0.3.0
>   │ ├── forever-agent@0.5.2
>   │ ├─┬ form-data@0.1.4
>   │ │ ├── async@0.9.2
>   │ │ └─┬ combined-stream@0.0.7
>   │ │   └── delayed-stream@0.0.5
>   │ ├─┬ hawk@1.0.0
>   │ │ ├── boom@0.4.2
>   │ │ ├── cryptiles@0.2.2
>   │ │ ├── hoek@0.9.1
>   │ │ └── sntp@0.2.4
>   │ ├─┬ http-signature@0.10.1
>   │ │ ├── asn1@0.1.11
>   │ │ ├── assert-plus@0.1.5
>   │ │ └── ctype@0.5.3
>   │ ├── json-stringify-safe@5.0.1
>   │ ├── mime@1.2.11
>   │ ├── node-uuid@1.4.7
>   │ ├── oauth-sign@0.3.0
>   │ ├── qs@0.6.6
>   │ └── tunnel-agent@0.3.0
>   ├── underscore@1.5.2
>   ├─┬ upnp-client@0.0.1
>   │ └── step@0.0.6
>   └─┬ xml2js@0.2.8
>     └── sax@0.5.8

**Comment by denisbr** [comment]
@stephen the PR from @Kolky works to resolve this problem, as confirmed by multiple users.

**Comment by olets** [comment]
Anyone have a working airsonos fork using @Kolky's nodetunes fix? I made one but for some reason (I think related to my nvm setup? but doesn't matter really) npm wasn't able to install it.

**Comment by chabicht** [comment]
@olets, I did like @isidore said: https://github.com/stephen/airsonos/issues/316#issuecomment-255663049.

My airsonos was installed from a working copy at commit https://github.com/stephen/airsonos/commit/9e7a3ca6cba9d678c303061660fc63c626e1da7a using `sudo npm install -g`.

Sound comes out of the speakers (tested with iOS 10 and macOS Sierra) but with my setup on a Raspi 3 Model B, the sound lags at least 3 seconds behind the device.
