### ISSUE TITLE
airsonos crashes when airplay source is apple tv 4

### ISSUE THREAD

**Issue by imerin** [stephen/airsonos#306]
two different results here:
/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233
      debug('uncaptured SET_PARAMETER method: %s', req.content.toString().trim());
                                                              ^

TypeError: Cannot read property 'toString' of undefined
    at setParameter (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:233:63)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at emitTwo (events.js:87:13)
    at ServerParser.emit (events.js:172:7)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/httplike/lib/parser.js:91:14)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at ServerParser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

and

/usr/local/lib/node_modules/airsonos/node_modules/ipaddr.js/lib/ipaddr.js:485
      throw new Error("ipaddr: the address has neither IPv6 nor IPv4 format");
      ^

Error: ipaddr: the address has neither IPv6 nor IPv4 format
    at Object.ipaddr.parse (/usr/local/lib/node_modules/airsonos/node_modules/ipaddr.js/lib/ipaddr.js:485:13)
    at options (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:28:31)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at emitTwo (events.js:87:13)
    at ServerParser.emit (events.js:172:7)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/httplike/lib/parser.js:91:14)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at ServerParser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by imerin** [comment]
I can confirm that the fix suggested in https://github.com/stephen/nodetunes/issues/39 fixes the issue.


changing line 233 in rtspmethods.js to
 var debugString;
 if ("content" in req) {
   debugString = req.content.toString().trim();
 } else {
   debugString = req.getHeader('Content-Type');
 }
 debug('uncaptured SET_PARAMETER method: %s', debugString);
