### ISSUE TITLE
airsonos always crashes on Mac with iTunes

### ISSUE THREAD

**Issue by Thr44** [stephen/airsonos#313]
hello, I had airsonos working perfectly until a mac update.

I start airsonos:
Searching for Sonos devices on network...

Lounge (@ 192.168.1.2:1400, RINCON_5CAAFD01591801400:0)

Search complete. Set up 1 device tunnel.

And then when I press play on itunes:

now I always get :

crypto.js:232
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:232:16)
    at Object.Decipheriv (crypto.js:229:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:540:8)

**Comment by Thr44** [comment]
it is similar to https://github.com/stephen/airsonos/issues/302 but occurs on my mac

**Comment by kevinelliott** [comment]
This happens for me as well.

**Comment by psieyes** [comment]
I'm trying to install AirSonos and each time I get to see my speakers and select for airplay, I get disconnected and iTunes reverts back to the internal speakers. I just can't get the AirSonos Airplay to work:
Searching for Sonos devices on network...

Office (@ 192.168.100.31:1400, RINCON_949F3E141E5401400:0)
Kitchen (@ 192.168.100.22:1400, RINCON_5CAAFD060AAC01400:1)

Search complete. Set up 2 device tunnels.
crypto.js:239
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:239:16)
    at Object.Decipheriv (crypto.js:236:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)

**Comment by kentakins** [comment]
@Thr44 I'm also on macOS Sierra and this fixed it for me: https://github.com/stephen/nodetunes/pull/42#issuecomment-261970525
