### ISSUE TITLE
Installation Help: Gyp fails due to Python 3?

### ISSUE THREAD

**Issue by basilweibel** [stephen/airsonos#326]
Really cool work! I am excited that my sonos might work with AirPlay! Unfortunately I fail at the installation. Any help much appreciated.

I use nvm to provide the old npm version:

```
My-MacBookPro:airsonos myusername$ nvm exec 0.12 node --version
Running node v0.12.16 (npm v2.15.1)
v0.12.16
```

Then the installation fails due to an unsupported python version? Any suggestions how I can fix that?

```
My-MacBookPro:airsonos myusername$ ls
CHANGELOG.md INSTALL.md   LICENSE      README.md    bin          index.js     lib          node_modules package.json
My-MacBookPro:airsonos myusername$ npm install -g

> airsonos@0.2.6 prepublish /Users/myusername/Downloads/airsonos
> babel ./lib/ -d ./bin/

lib/airsonos.js -> bin/airsonos.js
lib/diagnostics.js -> bin/diagnostics.js
lib/index.js -> bin/index.js
lib/tunnel.js -> bin/tunnel.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
/Users/myusername/.nvm/versions/node/v6.7.0/bin/airsonos -> /Users/myusername/.nvm/versions/node/v6.7.0/lib/node_modules/airsonos/bin/index.js

> mdns@2.3.3 install /Users/myusername/.nvm/versions/node/v6.7.0/lib/node_modules/airsonos/node_modules/mdns
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/anaconda/bin/python" is v3.4.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Users/myusername/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:14)
gyp ERR! stack     at /Users/myusername/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:493:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/myusername/.nvm/versions/node/v6.7.0/bin/node" "/Users/myusername/.nvm/versions/node/v6.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/myusername/.nvm/versions/node/v6.7.0/lib/node_modules/airsonos/node_modules/mdns
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
/Users/myusername/.nvm/versions/node/v6.7.0/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/myusername/.nvm/versions/node/v6.7.0/bin/node" "/Users/myusername/.nvm/versions/node/v6.7.0/bin/npm" "install" "-g"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdns
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/myusername/Downloads/airsonos/npm-debug.log
npm ERR! code 1
My-MacBookPro:airsonos myusername$ 
```

Also, are there any plans to make airsonos work with newer versions of npm, python and so on?

**Comment by basilweibel** [comment]
I had to do the following:

Install xCode. Then accept the licence:

`sudo xcodebuild -license`

Install airsonos with the python2.7 switch:
`sudo npm install airsonos -g --python=python2.7`

Fix the [crashes as described by isidore](https://github.com/stephen/airsonos/issues/316#issuecomment-255663049).
