### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 47.

### ISSUE THREAD

**Issue by wilfredphua** [stephen/airsonos#338]
My first install, I was able to run AirSonos but it wasn't detecting the Play:1 on the network. 
I then re-installed node and npm and ended up with this thrown exception. 
node -v v6.9.1
npm -v 3.10.8

Any help would be appreciated! 

/usr/local/lib/node_modules/airsonos/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/mdns/lib/mdns.js:1:77)

**Comment by gijoecool** [comment]
It looks like it's using node v5.x, not v6.x.

**Comment by wilfredphua** [comment]
oh snap does that mean i have too many versions of node installed?

**Comment by gnestor** [comment]
You just need to install/build airsonos with the same version that you run it with. If you still it with Node 5 and try to run it with Node 6, you will get this error.
