### ISSUE TITLE
Error during npm install (gyp ERR build error)

### ISSUE THREAD

**Issue by nicolastrognot** [stephen/airsonos#339]
Hello everybody,

I am trying to install airsonos on my Mac (El Capitan) to be able to let airplay working with my sonos.
I have downloaded the master branch, and run **npm install** but here is the compile error I have every times:

I have read lot of similar bug on the internet but nothing fixed mine.

Here is my config about node environment:

_Nicolas:airsonos-master Nicolas$ node -v_
**v6.9.1**
_Nicolas:airsonos-master Nicolas$ npm -v_
**3.10.8**
_Nicolas:airsonos-master Nicolas$ which node_
**/usr/local/bin/node**
_Nicolas:airsonos-master Nicolas$ env | grep PATH_
**PATH=/opt/local/bin:/opt/local/sbin:/Users/Nicolas/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin**

Here is the problem:

LIBTOOL-STATIC Release/libmp3lame.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/libmp3lame.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Nicolas/Downloads/airsonos-master/node_modules/lame
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
airsonos@0.2.6 /Users/Nicolas/Downloads/airsonos-master
└── sonos@0.7.0  (git://github.com/stephen/node-sonos.git#20d6d6afbf04d065330df6288c3db20234b515ce)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! lame@1.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lame@1.2.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lame package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lame
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lame
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Nicolas/Downloads/airsonos-master/npm-debug.log

**Comment by nicolastrognot** [comment]
Fixed with this command:
export PATH="/Library/Developer/CommandLineTools/usr/bin:$PATH
