### ISSUE TITLE
Working in Sierrs

### ISSUE THREAD

**Issue by Sathya1984** [stephen/airsonos#340]
Managed to get airsonos working in Sierra. In case you already have nodejs in your mac and are perplexed, please try below.

Step1:
Clear all node versions
sudo rm -rf /usr/local/{lib/node{,/.npm,_modules},bin,share/man}/{npm*,node*,man1/node*}

Step2:
Install node 0.10.28 (I tried other versions but only this one worked)
https://nodejs.org/en/blog/release/v0.10.28/

Step3:
Install airsonos:  
sudo npm install -g airsonos --unsafe-perm

Enjoy the music :)

**Comment by daysays** [comment]
Sweet! This worked perfectly. Thanks!

**Comment by gnestor** [comment]
Confirmed that this works! Thanks @Sathya1984!

**Comment by LwsBtlr** [comment]
I don't understand that version number. the node version I have is 7.2.1

**Comment by gnestor** [comment]
The versions have been incrementing very quickly since 0.10x! The easiest way to switch to Node 0.10x is to install [n](https://github.com/tj/n) (`npm install n -g`), then in the command line do `n 0.10.28` which will install Node 0.10.28 and then do `n` which will prompt you for which version of Node you want to switch to, and select "0.10.28". You can switch back to Node 7 by simply using the `n` command again and switch to 7.

**Comment by Doppelherz** [comment]
this doesn't work on my system. I removed all other node versions, installed 0.10.28 on mac os sierra, installed airsonos as described and started airsonos. After starting airsonos I've found my sonos speakers and selected them over airplay, it began to play at full volume for a few milliseconds, but then an error occured and shut down the airsonos tunnel. 

What went wrong?

**Comment by jonasvekeman** [comment]
I just got it working with the described steps on my system as well (macOS Sierra v10.12.2).
Thanks!

**Comment by mclinder** [comment]
Thank you. Has worked perfectly.

**Comment by dahuuhad** [comment]
It doesn't work for me, any ideas? According to the output below it finds my sonos but it doesn't show up anywhere. 
```bash-3.2$ airsonos --diagnostics
AirSonos Diagnostics
node version	 v0.10.28
operating sys	 darwin (x64)
ip address	 192.168.1.222

Searching for Sonos devices on network...

Device 	{"host":"192.168.1.127","port":1400,"state":{}} (ZPS6)
`- attrs: 	{"CurrentZoneName":"Living Room",
		"CurrentIcon":"x-rincon-roomicon:living",
		"CurrentConfiguration":"1"}
`- info: 	{"SoftwareVersion":"34.7-35162c",
		"DisplaySoftwareVersion":"7.0",
		"HardwareVersion":"1.13.1.7-2",
		"IPAddress":"192.168.1.127",
		"MACAddress":"XX:XX:XX:XX:XX:86",
		"CopyrightInfo":"© 2004-2015 Sonos, Inc. All Rights Reserved.",
		"ExtraInfo":"",
		"HTAudioIn":"0",
		"Flags":"0"}
`- topology: 	[{"group":"RINCON_5CAAFDF1538601400:0",
		"coordinator":"true",
		"wirelessmode":"1",
		"wirelessleafonly":"0",
		"hasconfiguredssid":"1",
		"channelfreq":"2472",
		"behindwifiext":"0",
		"wifienabled":"1",
		"location":"http://192.168.1.127:1400/xml/device_description.xml",
		"version":"34.7-35162c",
		"mincompatibleversion":"33.0-00000",
		"legacycompatibleversion":"25.0-00000",
		"bootseq":"7",
		"name":"Living Room"}]```

**Comment by seakerl** [comment]
> Sweet! This worked perfectly. Thanks! Any ideas on how to eliminate the delay? It's about five seconds.
Same here, works fine. Any ideas on how to fix the delay?

**Comment by gareaugorille** [comment]
Hi, it does not work for me either. 

I have applied the instructions above and installed AirSonos on a Mac mini (late 2014), running Sierra 10.12.3. 

Here is the output I get: 

> > PZOT:~ pzot$ airsonos --diagnostics
> AirSonos Diagnostics
> node version	 v0.10.28
> operating sys	 darwin (x64)
> ip address	 192.168.1.172
> 
> Searching for Sonos devices on network...

the system hangs, searching for the devices on the network. Any idea why this is happening? 

Thanks!

**Comment by AC94** [comment]
It worked great for me! Many thanks

**Comment by 4fkk** [comment]
Having had a similar problem to #341  I tried this suggestion a number of times  before it eventually worked.  I did disconnect my Sonos Dock as suggested by another thread so not sure if that was the cause or just coincidence.

**Comment by sashaparang** [comment]
Having some issues with Sierra 10.12.4.. the program runs fine and finds the device, I can change the output source, but as soon as I hit play for instance on SoundCloud it reverts back to the the laptop speaker and the Sonos source disappears. Is anyone else having this issue? 

﻿

**Comment by sashaparang** [comment]
Sashas-MBP:~ sashazinshtein$ airsonos
Searching for Sonos devices on network...

Living Room (@ 192.168.1.197:1400, RINCON_5CAAFD581CC201400:0)

Search complete. Set up 1 device tunnel.
crypto.js:239
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:239:16)
    at Object.Decipheriv (crypto.js:236:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:549:8)
Sashas-MBP:~ sashazinshtein$

**Comment by worthbak** [comment]
@sashaparang me too! not sure what the issue is, but I also haven't dug into it much...

**Comment by dyz2102** [comment]
I tried the solution but got stuck at the following:

```
npm http 304 https://registry.npmjs.org/react-tools
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm http 304 https://registry.npmjs.org/batch

> mdns@2.3.3 install /usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
```

Have tried reinstalling Node, restarting computer, still can't get it to work.

**Comment by dubzeebass** [comment]
Anybody have any ideas for High Sierra? Very disappointed to see that Airsonos/Sonoair find the speakers, but I can't change the output to any of them in any of the sound dialogs.
