### ISSUE TITLE
Handing playback over to Airsonos kills the airsonos process

### ISSUE THREAD

**Issue by jhs-ck** [stephen/airsonos#358]
I already applied the fix described in https://github.com/stephen/airsonos/issues/342
Now i can see the Airsonos Devices via iDevice. Handing over the Playback closes the Airsonos Process with the following Error Message:

Search complete. Set up 2 device tunnels.
crypto.js:239
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:239:16)
    at Object.Decipheriv (crypto.js:236:12)
    at Object.decryptAudioData (/usr/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)

Any Help?

**Comment by jhs-ck** [comment]
Debug Output:

`Search complete. Set up 2 device tunnels.
  nodetunes:server broadcasting mdns advertisement (for port 5001) +18ms
  nodetunes:rtsp received method OPTIONS (CSeq: 0)
  nodetunes:rtsp { cseq: '0',
  'dacp-id': 'AEDCAE88ED21454',
  'active-remote': '2325430311',
  'user-agent': 'AirPlay/310.17' } +17s
  nodetunes:rtsp received method OPTIONS (CSeq: 1)
  nodetunes:rtsp { cseq: '1',
  'dacp-id': 'AEDCAE88ED21454',
  'active-remote': '2325430311',
  'user-agent': 'AirPlay/310.17' } +148ms
  nodetunes:rtsp received method OPTIONS (CSeq: 2)
  nodetunes:rtsp { 'apple-challenge': 'YfOnJ2FwCh0VdjSsNB71ZQ==',
  cseq: '2',
  'dacp-id': 'AEDCAE88ED21454',
  'active-remote': '2325430311',
  'user-agent': 'AirPlay/310.17' } +3ms
  nodetunes:helper building challenge for YfOnJ2FwCh0VdjSsNB71ZQ== (ip: 2a0280710198f90047b2ccc828374bc6, mac: 54520023d689) +3ms
  nodetunes:helper computed challenge: 4QyJsdTkP35HhuzzhUTC5f7IixhCujUAlM83nLle2/54k8E5wOKIbYV2khAbzl4mL1giaNZTZMOXoLl19bWreJlxrui+8HWZPG3Dr3CI1+3d78D2EwFp7LVTmUMGXz7P3RuJf35KUZioVZIl0wVP5BP7q6yFRbxSlv7tUX4Un9BQTMV24WYyDXf8reje5NVqxJbYnysjP3X/fmXbpHzqYgW211mepIZ8aezRyqGiIYgXtaDL2RNXVLSM0UIvlJkGZkWTr2RUKSJOTaVBkBhWxzZTTS1eyR+jUtmhX/eZ5Ucn2F+x+2zaA1gULjD3/Ljalru88y4W9T11U6JkLECT1A== +132ms
  nodetunes:rtsp received method ANNOUNCE (CSeq: 3)
  nodetunes:rtsp { 'content-length': '700',
  'content-type': 'application/sdp',
  cseq: '3',
  'dacp-id': 'AEDCAE88ED21454',
  'active-remote': '2325430311',
  'user-agent': 'AirPlay/310.17' } +8ms
  nodetunes:rtspmethods v=0
  nodetunes:rtspmethods o=AirTunes 4244230485253901119 0 IN IP6 2a02:8071:198:f900:1c15:c42d:7f59:3733
  nodetunes:rtspmethods s=AirTunes
  nodetunes:rtspmethods i=Cédrics iPhone
  nodetunes:rtspmethods c=IN IP6 2a02:8071:198:f900:1c15:c42d:7f59:3733
  nodetunes:rtspmethods t=0 0
  nodetunes:rtspmethods m=audio 0 RTP/AVP 96
  nodetunes:rtspmethods a=rtpmap:96 AppleLossless
  nodetunes:rtspmethods a=fmtp:96 352 0 16 40 10 14 2 255 0 0 44100
  nodetunes:rtspmethods a=rsaaeskey:mz4pdlNWjVOnCBwh+V82NWtxykC9/EHGxbBmEDX78P6Z+ZgpTeTbJooxYYmVGIfChdVaVNi6UpL7amjUEGXmC9FHMqNbrT50WzrEHLOKHiZhFI5W22Yk078J8JMBnkkQaYTdOCQ9qYlHoc/0mWfdB6NM/e1b9kywDTSpG+uXDzGbuMFCi+IVHfsvgfdYhDlwRBFfRL2AUC1Y8283nN5t5QuWlia4u3c7fAybn/0AZnYrvoxQ8wiPP4ycov2lvIBVMYOrkGwemu9Q0mpCTOlRxNfi/7lyXKplOlB/PdOabGfDkGDUSWC2xbqOk3FNGXNsRrELz0cowZSGiJC+1sVhzQ==
  nodetunes:rtspmethods a=aesiv:QH7Z0MrA4bPil8Ewd6BLZQ==
  nodetunes:rtspmethods a=min-latency:11025
  nodetunes:rtspmethods a=max-latency:88200
  nodetunes:rtspmethods  +1ms
  nodetunes:rtspmethods client name reported (Cédrics iPhone) +100ms
  nodetunes:rtspmethods ipv6 usage detected +1ms
  nodetunes:rtspmethods client considered connected +6ms
  nodetunes:rtsp received method SETUP (CSeq: 4)
  nodetunes:rtsp { transport: 'RTP/AVP/UDP;unicast;mode=record;timing_port=58045;control_port=60969',
  cseq: '4',
  'dacp-id': 'AEDCAE88ED21454',
  'active-remote': '2325430311',
  'user-agent': 'AirPlay/310.17' } +16ms
  nodetunes:rtp starting rtp servers +1ms
  nodetunes:rtspmethods setting udp ports (audio: 9491, control: 5442, timing: 8643) +0ms
  nodetunes:rtsp received method RECORD (CSeq: 5)
  nodetunes:rtsp { cseq: '5',
  'dacp-id': 'AEDCAE88ED21454',
  'active-remote': '2325430311',
  'user-agent': 'AirPlay/310.17' } +3ms
  nodetunes:rtsp received method SET_PARAMETER (CSeq: 6)
  nodetunes:rtsp { 'content-length': '20',
  'content-type': 'text/parameters',
  cseq: '6',
  'dacp-id': 'AEDCAE88ED21454',
  'active-remote': '2325430311',
  'user-agent': 'AirPlay/310.17' } +101ms
  nodetunes:rtspmethods received text metadata (volume: -21.002514) +1ms
  nodetunes:rtsp received method FLUSH (CSeq: 7)
  nodetunes:rtsp { 'rtp-info': 'seq=24171;rtptime=3680579583',
  cseq: '7',
  'dacp-id': 'AEDCAE88ED21454',
  'active-remote': '2325430311',
  'user-agent': 'AirPlay/310.17' } +120ms
crypto.js:239
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:239:16)
    at Object.Decipheriv (crypto.js:236:12)
    at Object.decryptAudioData (/usr/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)
`

**Comment by jhs-ck** [comment]
I guees it is related to https://github.com/stephen/nodetunes/pull/42/files 

Just found this fix. Just try to implement it

**Comment by jhs-ck** [comment]
Now Working
