### ISSUE TITLE
bluebird throwing an error on clean install

### ISSUE THREAD

**Issue by mememan** [stephen/airsonos#359]
just installed on osx sierra latest.  Node LTS clean install then airsonos

reinstalled bluebird package in node just in case but getting this

/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/request/request.js:129:22)

**Comment by mememan** [comment]
fixed by RTFM ;-)
