### ISSUE TITLE
exception thrown....

### ISSUE THREAD

**Issue by steveschow** [stephen/airsonos#360]
I just installed npm (using brew) and then installed airsonos using your instructions (using npm).

OSX 10.11.6

Then I launched airsonos and got the following exception thrown:

sjs:[~]: sudo airsonos

Searching for Sonos devices on network...

/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)

**Comment by ankurokok** [comment]
Reproduced same issue on 10.11.6, node v6.8.1, npm v3.10.8

**Comment by steveschow** [comment]
this problem is perhaps solved by making sure to install node.js

Installer found here:

    https://nodejs.org/en/

**Comment by MaWel8** [comment]
I had the same problem. 
In my case there were outdated dependancies. After updating the dependancies with 
npm update -g
the problem was solved for me.
I hope it  will help you too.

**Comment by steveschow** [comment]
ran the update, getting a different exception now.  This is happening both on Mavericks and El Capitan:

Searching for Sonos devices on network...


/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:680
            throw e;
            ^
Error: Internal Server Error
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/request/request.js:129:22)

**Comment by rtvenge** [comment]
I fixed this issue for me. It happened when I added a Playbar and Playbase to my system, but I'm not sure which one created the issue.

I found [this solution](https://github.com/stephen/airsonos/issues/300#issuecomment-234733303) which has you replace a file in the `sonos` module. It seems to then account for "bridges" which maybe the playbase is seen as?

Anyway, not an ideal solution to replace files in node dependencies, but it did the trick for me for now.
