### ISSUE TITLE
Crypto Error

### ISSUE THREAD

**Issue by rickeames** [stephen/airsonos#362]
Running airsonos against 7.7.4, played from iOS 10.3, get:

crypto.js:241
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at new Decipheriv (crypto.js:241:16)
    at Object.Decipheriv (crypto.js:238:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:545:8)

**Comment by tommy60703** [comment]
same here :(

**Comment by danno-ax** [comment]
yep same :(

**Comment by nedjam** [comment]
I had this issue (MacOS 10.12.4). This solution fixed it for me: [https://github.com/stephen/airsonos/issues/316](https://github.com/stephen/airsonos/issues/316)

**Comment by lfilho** [comment]
Also try my comment here: https://github.com/stephen/airsonos/issues/342#issuecomment-295770479 This is what worked for me

**Comment by net4unner** [comment]
I just installed, had the exact same issue and [#316](https://github.com/stephen/airsonos/issues/316) corrected the crypto issue. Works great now!
