### ISSUE TITLE
Error: Invalid key length

### ISSUE THREAD

**Issue by 2ge** [stephen/airsonos#375]
```
Searching for Sonos devices on network...

Dining Room (@ 192.168.1.3:1400, RINCON_5CAAFDF48CCC01400:720103872)

Search complete. Set up 1 device tunnel.
crypto.js:265
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at new Decipheriv (crypto.js:265:16)
    at Object.Decipheriv (crypto.js:262:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:623:8)
```

**Comment by 2ge** [comment]
https://github.com/stephen/airsonos/issues/316#issuecomment-255663049
