### ISSUE TITLE
Device tunnels appear - I select sound outputs - but they disappear when playing sound

### ISSUE THREAD

**Issue by JediFrancis** [stephen/airsonos#377]
I am using Yosemeti on a 2012 MacBook Air. I have installed AirSonos and when I run it the device tunnels appear and and I am able to select them from the sound output selection. But as soon as I play any kind of audio (iTunes, movie file in VLC) the device tunnels disappear and the sound reverts to Internal Speakers.

Any thoughts? THANKS!!!

**Comment by luarockr** [comment]
same behavior here on early 2014 macbook air, error on console:

Error: Invalid key length
    at new Decipheriv (crypto.js:265:16)
    at Object.Decipheriv (crypto.js:262:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:619:8)
