### ISSUE TITLE
This command is not working. sudo npm install -g airsonos --unsafe-perm

### ISSUE THREAD

**Issue by EJGarba** [stephen/airsonos#378]
I follow all steps of installing Node.
I am on Sierra OS.
Please help.
Thanks

Error message.
Last login: Thu Jul 13 09:19:12 on ttys000
Eduardos-Mac-2:~ EduardoGarbarino$ sudo npm install -g airsonos --unsafe-perm
Password:
Sorry, try again.
Password:
npm http GET https://registry.npmjs.org/airsonos
npm http 304 https://registry.npmjs.org/airsonos
npm http GET https://registry.npmjs.org/babel
npm http GET https://registry.npmjs.org/flags
npm http GET https://registry.npmjs.org/nicercast
npm http GET https://registry.npmjs.org/ip
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/nodetunes
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/stephen/node-sonos.git) xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone git://github.com/stephen/node-sonos.git xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Error: Command failed: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:647:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:753:16)
npm ERR!     at Socket.<anonymous> (child_process.js:966:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 16.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "airsonos" "--unsafe-perm"
npm ERR! cwd /Users/EduardoGarbarino
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code 1
npm http 304 https://registry.npmjs.org/babel
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/nicercast
npm http 304 https://registry.npmjs.org/flags
npm http 304 https://registry.npmjs.org/ip
npm http 304 https://registry.npmjs.org/nodetunes
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/EduardoGarbarino/npm-debug.log
npm ERR! not ok code 0
Eduardos-Mac-2:~ EduardoGarbarino$ airsonos
-bash: airsonos: command not found
Eduardos-Mac-2:~ EduardoGarbarino$ npm install airsonos -g
npm http GET https://registry.npmjs.org/airsonos
npm http 304 https://registry.npmjs.org/airsonos
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/airsonos',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 16.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/EduardoGarbarino
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path /usr/local/lib/node_modules/airsonos
npm ERR! fstream_path /usr/local/lib/node_modules/airsonos
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/airsonos'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 16.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "airsonos" "-g"
npm ERR! cwd /Users/EduardoGarbarino
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/EduardoGarbarino/npm-debug.log
npm ERR! not ok code 0
Eduardos-Mac-2:~ EduardoGarbarino$ sudo npm install -g airsonos --unsafe-perm
npm http GET https://registry.npmjs.org/airsonos
npm http 304 https://registry.npmjs.org/airsonos
npm http GET https://registry.npmjs.org/flags
npm http GET https://registry.npmjs.org/babel
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/nicercast
npm http GET https://registry.npmjs.org/ip
npm http GET https://registry.npmjs.org/nodetunes
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/stephen/node-sonos.git) xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone git://github.com/stephen/node-sonos.git xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Error: Command failed: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:647:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:753:16)
npm ERR!     at Socket.<anonymous> (child_process.js:966:11)
npm ERR!     at Socket.EventEmitter.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 16.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "airsonos" "--unsafe-perm"
npm ERR! cwd /Users/EduardoGarbarino
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code 1
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/ip
npm http 304 https://registry.npmjs.org/nicercast
npm http 304 https://registry.npmjs.org/flags
npm http 304 https://registry.npmjs.org/babel
npm http 304 https://registry.npmjs.org/nodetunes
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/EduardoGarbarino/npm-debug.log
npm ERR! not ok code 0

**Comment by EJGarba** [comment]
Can someone give me a hand on how to solve this issue. I been reading different solutions but I keep getting the same problem. See error above.
Thanks.

**Comment by nnmalex** [comment]
I've got the same issue.
