### ISSUE TITLE
airsonos crashes after selecting a device in sound preferences

### ISSUE THREAD

**Issue by hectorgoan** [stephen/airsonos#382]
So... this happened.
![captura de pantalla 2017-09-06 a las 10 31 17](https://user-images.githubusercontent.com/5213294/30102163-0894c1d6-92ef-11e7-8d1a-8a4e4a3b49d5.png)

**Comment by stephankreft** [comment]
having the exact same problem

**Comment by sopitz** [comment]
+1 me too

**Comment by sopitz** [comment]
the workaround in this comment fixes it for me: https://github.com/stephen/airsonos/issues/316#issuecomment-255663049

**Comment by kof** [comment]
same here, trying the workaround next

**Comment by maikischa** [comment]
Same here in ubuntu 1710

```
airsonos 
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Searching for Sonos devices on network...

Bad (@ 192.168.1.31:1400, RINCON_XXXXXXXXXXXXXXXXX:XXXXXXXXX)
Küche (@ 192.168.1.32:1400, RINCON_XXXXXXXXXXXXXXXXX:00)
Wohnzimmer (@ 192.168.1.30:1400, RINCON_XXXXXXXXXXXXXXXXX:0)

Search complete. Set up 3 device tunnels.
crypto.js:242
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:242:16)
    at Object.Decipheriv (crypto.js:239:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)

```
