### ISSUE TITLE
AirSonos + High Sierra

### ISSUE THREAD

**Issue by dubzeebass** [stephen/airsonos#383]
Hi there,

Got everything all loaded, the hashes show up in the Terminal app, but I can't select output to any of the Sonos in any Sound dialog in 10.13.

Anyone have any ideas for a workaround? Im thinking it has to do with AirPlay 2. Love to find a workaround!!!

**Comment by crhuber** [comment]
this still worked for me in High Sierra http://sonoair.mihosoft.eu/

**Comment by dubzeebass** [comment]
I have 2x Sonos Play 3, and 1x Sonos Play 1. All on the same network. They aren't showing up! Any ideas?

I, too, am using SonoAir.

**Comment by dubzeebass** [comment]
![image](https://user-images.githubusercontent.com/32390170/31035112-c7c56568-a534-11e7-89ce-7fd9d029ed9a.png)

**Comment by dubzeebass** [comment]
The LED button in the settings for those different speakers does turn on and off the LED, so they're talking to each other. OSX just doesn't see them as an AirPlay speaker.

**Comment by miho** [comment]
SonoAir uses airsonos for the audio stream, i.e., airplay while the code for controlling the sonos speakers (volume and LED) is implemented in Java.

**Comment by MorsePacific** [comment]
I'm having the same issue; just installed AirSonos after finding out about it, but upgraded to High Sierra a few days ago. Install seemed to go just fine but I can't select any speakers from MacOS.

**Comment by pwhitey** [comment]
Have reinstalled homebrew, node and airsonos and can report the same problem. Sets up the tunnel for my two devices but they don't show as output devices.

**Comment by DigitalCaveman** [comment]
Having the same problem! Weird thing is that when I quit airsonos with 'ctrl+c' my sonos PLAY:1 shows up for a second but doesn't when airsonos is running.

**Comment by kilsen** [comment]
Having the same problem. MacBook Pro with Mac OS High Sierra. Tunnels are opened, but they don't appear on my Mac as available output devices. My iPhone shows them, but when I attempt to select one on my iPhone, airsonos crashes on the Mac with the following error:

crypto.js:238
  this._handle.initiv(cipher, toBuf(key), toBuf(iv));
               ^

Error: Invalid key length
    at Error (native)
    at new Decipheriv (crypto.js:238:16)
    at Object.Decipheriv (crypto.js:235:12)
    at Object.decryptAudioData (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/helper.js:141:25)
    at RtpServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtp.js:32:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:540:8)

**Comment by philippe44** [comment]
As @stephen does not seem to maintain it, you can try my version here https://github.com/philippe44/AirConnect. I don't know if it works on High Sierra, I have not tested

**Comment by miho** [comment]
@philippe44 congrats! Works fine for me. I also like the amount of work you put into the CLI. I am thinking about adding AirConnect support to SonoAir as an alternative to airsonos.

@pwhitey just use the binaries in the bin folder. After downloading/cloning this repository the following commands should be sufficient:

```bash
cd /path/to/AirConnect/bin
chmod +x airupnp-osx-multi
./airupnp-osx-multi
```

**Comment by pwhitey** [comment]
@philippe44 I can give it a test - does AirConnect install through npm or brew? thanks

**Comment by kilsen** [comment]
@philippe44 I tried it with my High Sierra. The Sonos speakers appear as audio output devices. The IP address of each Sonos speaker pair appears, but not the room name. I can surely work around that. But once I select a Sonos as the output device, the sound comes through, but very "choppy" -- it's as if someone is continuously toggling it on and off.

**Comment by philippe44** [comment]
Yes, it's probably related to buffering. Did you set the latency parameters to at least by adding -l 1000:2000 to the command line?

**Comment by rkpatel33** [comment]
@philippe44 Works great for me too on macOS HighSierra, thanks! The responsiveness is very snappy.

It was a little unclear how to use it, would be worthwhile dressing up the README a bit, but thanks for this!

**Comment by philippe44** [comment]
Can you help me by telling what was unclear in the README? What should I change?

**Comment by rkpatel33** [comment]
For me, it was not clear that there were runnable binaries in the `bin/`
folder, so I keep looking for installation instructions. So maybe just some
explanation on that, including these commands:

cd /path/to/AirConnect/bin
chmod +x airupnp-osx-multi
./airupnp-osx-multi


Maybe even instructions on re-compiling for those who are not familiar with it.




_________________________
Rishi Patel | mail@rishinyc.com

**Comment by kilsen** [comment]
@philippe44 I added "-l 1000:2000" to the command line and that seems to have solved the buffering issue. I also produced a config file (using "-i") and then edited the names in the XML file so that they reflect the "friendly" names of the Sonos speakers (i.e., the Rooms). Note that the "-x" command line option seems to require that I also specify the name of the config file; if I simply name the file "config.xml" in the current directory (the default according to the -h command line help), I get a Segmentation fault: 11.

**Comment by philippe44** [comment]
The -x switch requires a filename. If you want to use "config.xml", as a default, don't specify -x at all. I agree that it should not segfault, still :-) I'll correct that in next release

**Comment by Cristhian12T** [comment]
@philippe44 Hello, I've seen that it worked for soo many people, your solution must had been great, I tried to run everything you explain but I am not very familiar with most of the things you talk about, I BEG YOU, CAN YOU PLEASE EXPLAIN IT TO ME STEP BY STEP, I WOULD BE SUPER HAPPY IF U CAN HELP ME. 
This is my mail: cristhian.grisales@outlook.es
Whatsaap: +34608426735
Please contact me, thank you...

**Comment by philippe44** [comment]
Can you describe your OS and at what stage/step you are stuck

**Comment by Cristhian12T** [comment]
Hi, thanks for replying. I literally don't know how to start, I downloaded everything you have in the website but I need help to make it run.
![1510708632399617478085](https://user-images.githubusercontent.com/33674616/32813548-bf013aa0-c9a2-11e7-84bf-1b01b78c2b62.jpg)

**Comment by Cristhian12T** [comment]
@philippe44  I answer the message in the prevues comment

**Comment by philippe44** [comment]
I'm not a Mac OS expert, but you should download the airupnp.zip (the latest version) and probably, put it in any folder and click on it or right click on it so that it opens. There you should be able to extract the airupnp-osx-multi. The I suggest you google 'macOS how to make a file executable' and follow the instructions you find. If you don't find anything suitable, google 'MacOS how to open a terminal' and then go to the folder folder where you have extracted the file and follow the instructions again on the readme

**Comment by Cristhian12T** [comment]
Thank you @philippe44  I will try it tomorrow as soon as I can, I will let u know how it goes, thanks.

**Comment by Cristhian12T** [comment]
Ok I dowloaded the airupnp.zip, I opened it and executed the airupnp-osx-multi, now from this step what alse shall I do... @philippe44 
<img width="574" alt="screen shot 2017-11-16 at 02 18 11" src="https://user-images.githubusercontent.com/33674616/32870626-bb48d1d4-ca74-11e7-83fc-1b1cb0d2eb8f.png">
<img width="674" alt="screen shot 2017-11-16 at 02 12 18" src="https://user-images.githubusercontent.com/33674616/32870628-bcb9a426-ca74-11e7-8c50-8b2b00b27006.png">

**Comment by Cristhian12T** [comment]
@philippe44 please help me with a video tutorial showing how u do it please...

**Comment by Cristhian12T** [comment]
@miho  Hi Michael, please can you help me understand the steps I have to follow in the solution of @philippe44, you would make my life very happy, I cant use the sonos unless it be with the app, and it is crap... thanks

**Comment by stephenjharrington** [comment]
@miho said "I am thinking about adding AirConnect support to SonoAir as an alternative to airsonos".

This would be a GREAT development and would be much appreciated Michael. Your SonoAir GUI front end and @philippe44 's AirConnect code could be the perfect pairing?

StephenH

**Comment by crabicode** [comment]
I can confirm that `osx 10.13.1` and `airsonos 0.2.6` finds the device, but nothings seems to show up in the output devices.

**Comment by philippe44** [comment]
@Cristhian12T: you're using the wrong application. This one (AirCast) is for ChromeCast devices; Use airupnp-osx-multi instead and you should be good to go

**Comment by pulokidy** [comment]
I tried mine, and it didn't work as well, my imac is mid 2011, would that be the problem? i have updated to latest OSX.... using airupnp-osx-multi

**Comment by psyenz** [comment]
Got everything loaded and running but with a caveat: the latency adjusts in the wrong direction.  If I set  http latency to anything greater than 0, the audio gets further out of sync.  If set to 0, there is about a 2 second delay.  If I try setting to a negative number, then there is no audio.  Any ideas?  (this is on a MacBook Pro)

**Comment by philippe44** [comment]
if you're talking about airconnect, this is the wrong place. But even if this is about airsonos, you cannot have audio/video synchronization with such solutions. It's simply impossible due to the nature of the bridging being done (sync RTP to async HTTP)

**Comment by wesleymostien** [comment]
when you disconnect, the device tunnels briefly appear in the sound setting dialog

**Comment by abulgatz** [comment]
Is there any work being done to get AirSonos working with macOS 10.13 High Sierra?

**Comment by rafale77** [comment]
Finding these reports very weird... I am not able to reproduce the problems you are seeing. I have been using Airsonos with High Sierra and all the other OSX versions before this without any problem. No SonoAir, No Airconnect... just launched the server on a headless ubuntu VM.

**Comment by pockey04** [comment]
I have followed this thread and have been able to add the play 1 to output. However, when I exist out of the terminal (Osx high sierra) the sound disappears and when it does play its very choppy despite the addition of -1 1000:2000. Any recommendations?

**Comment by philippe44** [comment]
It's letter l (L) not the number -1

**Comment by pockey04** [comment]
Wow! Thanks so much. Will make the changes. Will that also resolve the exit issue?


Thanks


G
