### ISSUE TITLE
Error when running El Capitan 10.11.6 sonos v8.0

### ISSUE THREAD

**Issue by helio58** [stephen/airsonos#386]
Getting this error
Any suggestions?
Thanks 

Searching for Sonos devices on network...

Rum (@ 192.168.2.102:1400, RINCON_5CAAFD48829A01400:907790755)

Search complete. Set up 1 device tunnel.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)

**Comment by philippe44** [comment]
Hi - I've been using AirSonos at the beginning and then I created a similar application, works as a generic solution for UPnP (there is a version for Chromecast as well). 

NB: I have no intention to be disrepectful of the work made by stephen and/or "troll" his github. I'll remove this comment immediately is considered as such. I'm posting here because I've seen the application has not been updated for a long while, and I want to help others. My app is free as well

**Comment by helio58** [comment]
Thank you Philippe44,

Will try later, with your app i can send the audio to the sonos system too?
Once more thank you

**Comment by philippe44** [comment]
Yes it does work - Sonos are speakers are fully UPnP compliant

**Comment by helio58** [comment]
Yes tested working 110%  THANK YOU
