### ISSUE TITLE
Pre-built Windows Package

### ISSUE THREAD

**Issue by stephen** [stephen/airsonos#59]
Experimental pre-built airsonos package and instructions found here: https://github.com/stephen/airsonos/releases/tag/0.0.19

Please report issues here.

**Comment by vestibule1443** [comment]
Hi Stephen, thanks for making this. I have a bit of help that will get people at least one step further, but I'm also stuck.

When people run the airsonos commond and they get: "searching for sonos devices on the network..." and then nothing else, they should exit and reopen the command prompt. I had the same issue but the second time I ran the command the windows firewall notice popped up and let me allow airsonos through. 

This is where I'm stuck though, after it found the device on the network it says "setting up Airsonos for Living Room (ip address) but then it doesn't do anything else. I don't have any other wireless devices other than my laptop so I don't know what to test. What should I do?

**Comment by vikrora** [comment]
Hi Stephen,

Thanks for making this happen. I started feeling dishearted after making my first purchase of play 1 speaker.

Kudos to you man. 

I have installed airsonos on windows and it worked like gem. Thanks to your clear cut instructions. I have only a small issue, don't know if that's already been answered.

Songs stop streaming  on airsonos when iOS device is locked. 

Please suggest if you have any wok around for this.

Thanks,

**Comment by stephen** [comment]
@vikrora - Hmm, I think your iOS issue probably belongs in its own thread, since I don't think it's directly related to the Windows build.

This shouldn't be happening though, perhaps the connection on your device is not great?

**Comment by Muck1ng** [comment]
Hi,

I have a problem, when listening to audiobook after about 2 minutes the audio will cut out but continue to play on the phone, it will then start again but I'll have missed 30 seconds of audio?

**Comment by bleachisback** [comment]
I think this is a great idea, but I have a bit of a problem. When I run airsonos it tells me that it's found my device, and then I see it pop up on my ipad, but whenever I select it, it immediately selects the ipad again.

Occasionally the speaker stays selected, but then no sound is ever played (or ever makes progress on the ipad - like youtube won't even play the video).

**Comment by bleachisback** [comment]
Actually, [this](https://github.com/stephen/airsonos/issues/93#issuecomment-70770093) was able to solve my problem. Disabling my wireless network adapter made it work perfectly.

Love the software!

**Comment by daniel1981** [comment]
Hi,

I tried to install airsonos on a windows xp machine.
When I try to start airsonos, I get the following messages:
```
C:\Dokumente und Einstellungen\Administrator\Anwendungsdaten\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:35
    throw ex;
          ^
Error: no errorC:\Dokumente und Einstellungen\Administrator\Anwendungsdaten\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\build\Release\dns
_sd_bindings.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Dokumente und Einstellungen\Administrator\Anwendungsdaten\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\d
ns_sd.js:24:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
Can anyone help me with this problem?

Thanks

Dnaiel

**Comment by detond** [comment]
I got the following error with NodeJS (32 bit)... Anybody can help me?

```
C:\Users\mail_000\AppData\Roaming\npm>airsonos
C:\Users\mail_000\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetun
es\node_modules\mdns\lib\dns_sd.js:35
    throw ex;
          ^
Error: The specified procedure could not be found.
C:\Users\mail_000\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetun
es\node_modules\mdns\build\Release\dns_sd_bindings.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\mail_000\AppData\Roaming\npm\node_modules\ai
rsonos\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:24:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

C:\Users\mail_000\AppData\Roaming\npm>```

**Comment by Seanom** [comment]
I'm experiencing a similar issue to Daniel, but using windows 8.1

    C:\Users\Sean>airsonos
    C:\Users\Sean\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:35
    throw ex;
          ^
    Error: no errorC:\Users\Sean\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\build\Release\dns_sd_bindings.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Sean\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:24:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by bimbog** [comment]
Hi Stephen, i found this error.. is there any way to solve it?

C:\Windows\system32>airsonos
C:\Users\dabinlo\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetune
s\node_modules\mdns\lib\dns_sd.js:35
    throw ex;
          ^
Error: The specified procedure could not be found.
C:\Users\dabinlo\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetune
s\node_modules\mdns\build\Release\dns_sd_bindings.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\dabinlo\AppData\Roaming\npm\node_modules\air
sonos\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:24:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by TAS92** [comment]
Hi Stephen,

Thanks for this...it's amazing!

I had no problems setting this up on a Windows 8.1 PC and subsequently streaming from my iOS devices to my Sonos system.

The only issue I'm having is getting my PC audio directly to Sonos speakers. After I run "Airsonos" from the command prompt it shows up on the Sonos PC software as a streaming radio station, but will not connect. What seems odd is that the IP address of my Sonos component shown on the command prompt is different than that of the one shown in the Sonos software.

I have also tried to get the PC system audio to Sonos via programs like Airfoil. The Sonos components show up, but again will not connect.

Any ideas? Thanks in advance!

**Comment by nicka99** [comment]
hi Stephen
I followed the instructions above and no errors during installation but when I type 'where sonos' I get error "INFO: Could not find files for the given pattern(s)."

its windows 7 64 bit but I guess it should also run this in 32 bit ?

any ideas ?

**Comment by matasn** [comment]
Hello Stephen, after some idle time of not streaming to my Sonos speaker I cannot make it to work again. The only way I can fix this is by rebooting my PC.

Any help or easier workaround to fix this issue (without rebooting my PC) is greatly appreciated it.

By the way, I can see that for OS platform the current version is 0.1.1, are there any plans to update the non-OS platforms versions any time soon?

Thank you for this tool it works great, and I'm not frustrated anymore with my Sonos purchase because of Airsonos :)

**Comment by sonnyshogun** [comment]
Hi Stephen

Installed the software on a Windows 7 pc and started it up. It found all the sonos speakers and I could choose them in iTunes. When I try to select the sonos speakers it comes only "interference" sound for a while but not any of the music playing in iTunes. What am I doing wrong?

Thanks in advance!

**Comment by dekgray** [comment]
Hi Stephen. thank you for creating this solution to Airplay with Sonos. I've done everything correctly with the set up but am unable to get any further than the command line reporting 'Setting up Airsonos for [my speaker \ ip address:port]' Actually, it reports two speakers as I have two Play1's set up as a stereo pair. 
My iPad (running Plex) displays each speaker in the Airplay icon, but when i select either one, although the icon changes to blue (which usually would indicate the connection has been made) there is no sound and indeed playback freezes!
I've tried switching off Windows Firewall, I've created rules to open the port (1400) including on the router. I've tried rebooting everything, restarting the CMD and Airsonos at the prompt, but I just can't get beyond the 'Setting up Airsonos for ...' message.
Any help would be so much appreciated, including if possible, how to fix the two speakers showing separately.

**Comment by h1jfg** [comment]
Hi Stephen,
First off just want to say fantastic work on this solution!
I have installed everything as per instructions on a WIndows 7 64-bit PC and everything seems to work okay. Airsonos finds my Sonos Play 1 speaker and I can select it from my iPad Air as an Airplay device. However  ..... when playing music it will skip frequently (using Google Play streaming). I will download music to my iPad and try again (to eliminate Google Play streaming as the issue). But just wondered if anyone else has experienced this skipping issue and found a fix. 
My PC has direct Ethernet connection (1Gbps) to Wireless router and I am using a Sonos Bridge connected directly to the same router.

**Comment by t3chn0m4g3** [comment]
@stephen thank you very much for airsonos! really made my day :smile: 

For the Windows version I ran into the following issue:
- Airsonos would start but was unable to discover any of my Sonos devices

Solution:
- Right click "Network" on desktop > Select "Properties" > Click "Change adapter settings"
- Right click the LAN adapter > Select "Properties" > Uncheck "Internet Protocol Version 6" > Click "OK" and repeat this step for ALL network adapters

**Comment by kawasakizx10rr** [comment]
I had the problem that it would not find my speaker, It was not the firewall but windows defender "real-time protection", :) 

but now it is WAI what do i do to get youtube to work on my sonos or as my default speaker for my pc as it only shows my sound card at the moment

**Comment by atwoodjw** [comment]
Any chance for an updated Windows build, now that 0.2.5 is out w/ iOS 9 & El Capitan support?

**Comment by Kidtwist** [comment]
I have a wired desktop computer on a network that also includes wifi devices. Will this work on that computer or does the computer have to be on wifi to interact with the Sonos speakers? Thanks.

**Comment by hjfcfo** [comment]
I installed the windows 7 and see the sonos devices in airplay list.  I select 1 and get loud static only.  ??

**Comment by hindsc52** [comment]
I also receive this error on windows 10

C:\Users\chind>airsonos
C:\Users\chind\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetunes\
node_modules\mdns\lib\dns_sd.js:35
    throw ex;
    ^

Error: The specified procedure could not be found.
\\?\C:\Users\chind\AppData\Roaming\npm\node_modules\airsonos\node_modules\nodetu
nes\node_modules\mdns\build\Release\dns_sd_bindings.node
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\chind\AppData\Roaming\npm\node_modules\airso
nos\node_modules\nodetunes\node_modules\mdns\lib\dns_sd.js:24:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by FrazerE** [comment]
HI Stephen,  firstly thanks for the work on Airsonos it's a great idea.    I've installed and run on windows 10 and my command box shows:
Searching for Sonos devices on network...
Setting up AirSonos for Dining Room {192.168.0.104:1400}
Setting up AirSonos for Kitchen {192.168.0.103:1400}

Hurrah!  however I can't see the airplay speakers in iOS on ipad and apple TV.  they only show up in iTunes on the Windows 10 PC... and when selected only play static/white noise... are there any workarounds?

Windows 10 pro
Node 0.10.33
Bonjour SDK 3.0.0.10
iTunes 12.4.0.119
iOS 9.3.2

**Comment by daranto** [comment]
Hey,

I have the same issue like FrazerE. Did anyone find a solution for this?

Daranto

**Comment by Tom741** [comment]
I have the Same problem as daranto and FrazerE was there any solution?

**Comment by wubin2** [comment]
error on win7 

`C:\Users\win7>airsonos
Unexpected result while probing for avahi: { [Error: dns service error: unknown]
 errorCode: -65537 }
Searching for Sonos devices on network...
Setting up AirSonos for Studio {192.168.1.145:1400}

Error: dns service error: unknown
    at objectToTXTRecord (C:\Users\win7\AppData\Roaming\npm\node_modules\airson
os\node_modules\nodetunes\node_modules\mdns\lib\advertisement.js:80:12)
    at new Advertisement (C:\Users\win7\AppData\Roaming\npm\node_modules\airson
os\node_modules\nodetunes\node_modules\mdns\lib\advertisement.js:36:17)
    at Object.create [as createAdvertisement] (C:\Users\win7\AppData\Roaming\np
m\node_modules\airsonos\node_modules\nodetunes\node_modules\mdns\lib\advertiseme
nt.js:64:10)
    at NodeTunes.<anonymous> (C:\Users\win7\AppData\Roaming\npm\node_modules\ai
rsonos\node_modules\nodetunes\lib\server.js:65:21)
    at Server.g (events.js:180:16)
    at Server.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)`

**Comment by madpiano** [comment]
Hi, not sure if anyone still interested in this method...I'm having the same problem as one of the above. Looks like AirSonos is being set up, but it's still not showing up on my Iphone. I don't have a way to check Bonjour devices, because the only thing I have is Iphone and Ipad.

Searching for Sonos devices on network...
Setting up AirSonos for Living {192.168.0.5:1400}

**Comment by SiddharthLucky** [comment]
> Hi Stoelman,
> 
> I have the same issue as you - airsonos is searching for my sonos devices but does not find anything
> 
> Jon

I am currently experiencing the same issue, has there been a resolution for this yet?
