### ISSUE TITLE
airsonos didn´t start because of dns service error: unknown

### ISSUE THREAD

**Issue by Zigulle** [stephen/airsonos#77]
Hello,

i try to start airsonos on a banana pi. Every thing during the installation worked fine. But when I start airsonos, I will get the following output:

Setting up AirSonos for Küche {10.0.0.22:1400}

Error: dns service error: unknown
    at new Advertisement (/opt/node/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/opt/node/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/mdns/lib/advertisement.js:64:10)
    at NodeTunes.<anonymous> (/opt/node/lib/node_modules/airsonos/node_modules/nodetunes/lib/server.js:74:21)
    at Server.g (events.js:180:16)
    at Server.EventEmitter.emit (events.js:92:17)
    at net.js:1055:10
    at process._tickCallback (node.js:419:13)

Any help?

Thanx, Daniel

**Comment by kekiefer** [comment]
Check that your avahi-daemon is running (correctly). In my case, after an upgrade, dbus was failing to start, so avahi-daemon couldn't initialize.
