### ISSUE TITLE
"npm update -g" results in loss of bindings file

### ISSUE THREAD

**Issue by wesleythill** [stephen/airsonos#84]
After running npm update -g, executing airsonos results in:

/usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/build/bindings.node
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/build/Debug/bindings.node
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/build/Release/bindings.node
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/out/Debug/bindings.node
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/Debug/bindings.node
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/out/Release/bindings.node
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/Release/bindings.node
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/build/default/bindings.node
 → /usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/compiled/0.10.33/darwin/x64/bindings.node
    at bindings (/usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nicercast/node_modules/lame/lib/decoder.js:7:15)
    at Module._compile (module.js:456:26)

**Comment by stephen** [comment]
Hmm, were you able to solve this, apart from doing a reinstall? Perhaps a `npm rebuild`?

**Comment by wesleythill** [comment]
I have never tried the npm rebuild, just reinstall. I will give it a go
next time it happens.

On another note, thanks for this cool resource. Stoked to have this ability.

**Comment by maxime-crunding** [comment]
I reinstall and it worked again.

**Comment by stephen** [comment]
Hmm, I wasn't able to reproduce this when upgrading to 0.0.26 just now. (`sudo npm update -g airsonos`?)
